bin/orcabus.ts
config/constants.ts
lib/workload/orcabus-stateful-stack.ts
lib/workload/orcabus-stateless-stack.ts
lib/workload/stateful/database/component.ts
lib/workload/stateful/eventbridge/component.ts
lib/workload/stateful/schemaregistry/component.ts
lib/workload/stateful/securitygroup/component.ts
lib/workload/stateless/bcl_convert/component.ts
lib/workload/stateless/schema/component.ts

* Minor refactored and improved arrangement

Implemented externalise config constants pass-down as props pattern

---

.eslintrc.json
.pre-commit-config.yaml
Makefile
README.md
bin/orcabus.ts
config/constants.ts
jest.config.js
lib/workload/orcabus-stateful-stack.ts
lib/workload/orcabus-stateless-stack.ts
lib/workload/stateful/database/component.ts
lib/workload/stateful/eventbridge/component.ts
lib/workload/stateful/schemaregistry/component.ts
lib/workload/stateful/securitygroup/component.ts
lib/workload/stateful/vpc/component.ts
lib/workload/stateless/bcl_convert/component.ts
lib/workload/stateless/layers/component.ts
lib/workload/stateless/layers/create_layer_package.sh
lib/workload/stateless/schema/component.ts
package.json
test/orcabus.test.ts
yarn.lock

* Bumped Python3.10
* Updated README and Makefile

Bumped dependencies and fixed lints

---

.github/workflows/prbuild.yml
Makefile
requirements-dev.txt

* Added GitHub Action workflow for PR Build - pre-stage to CodePipeline
* It will run past check Makefile targets
* make check -- Any issue lint, formatter
* make test  -- Run unit test suite
* It also run TruffleHog scanner as last checkpointing

Reinforced DevSecOps setup with scanners TruffleHog & GGShield

---

bin/orcabus.ts
config/constants.ts
lib/workload/orcabus-stateful-stack.ts
lib/workload/stateful/database/component.ts
lib/workload/stateful/eventbridge/component.ts
lib/workload/stateful/securitygroup/component.ts

- Attempt on changing to Serverless MySQL

Serverless MySQL

---

config/event_schemas/SequenceRunStateChange.json

* Wrapped into proper Event envelope
* Refactored domain event payload into component schema
definition `SequenceRunStateChange`
* Namespaced X-header event source to `orcabus.srm`

Updated SequenceRunStateChange Event schema with proper envelope

---

skel/django-api/src/migrate.py
skel/django-api/src/project_name/wsgi.py
skel/django-api/src/project_name_proc/lambdas/hello_proc.py
skel/django-proc/src/migrate.py
skel/django-proc/src/project_name_proc/lambdas/hello_proc.py

* Deployed target must set `DJANGO_SETTINGS_MODULE` env var
to `aws` setting. Else, it is better that let it crash by default.
* See #28 convo.

Improved Django Skel by removing base setting as default

---

docs/developer/SRM.md
lib/workload/stateless/sequence_run_manager/src/migrate.py
lib/workload/stateless/sequence_run_manager/src/requirements.txt
lib/workload/stateless/sequence_run_manager/src/sequence_run_manager/management/commands/generate_mock_bssh_event.py
lib/workload/stateless/sequence_run_manager/src/sequence_run_manager/management/commands/generate_mock_domain_event.py
lib/workload/stateless/sequence_run_manager/src/sequence_run_manager/wsgi.py
lib/workload/stateless/sequence_run_manager/src/sequence_run_manager_proc/domain/sequence.py
lib/workload/stateless/sequence_run_manager/src/sequence_run_manager_proc/domain/sequencerunstatechange/AWSEvent.py
lib/workload/stateless/sequence_run_manager/src/sequence_run_manager_proc/domain/sequencerunstatechange/SequenceRunStateChange.py
lib/workload/stateless/sequence_run_manager/src/sequence_run_manager_proc/domain/sequencerunstatechange/__init__.py
lib/workload/stateless/sequence_run_manager/src/sequence_run_manager_proc/domain/sequencerunstatechange/marshaller.py
lib/workload/stateless/sequence_run_manager/src/sequence_run_manager_proc/lambdas/bssh_event.py
lib/workload/stateless/sequence_run_manager/src/sequence_run_manager_proc/tests/case.py
lib/workload/stateless/sequence_run_manager/src/sequence_run_manager_proc/tests/test_bssh_event.py
lib/workload/stateless/sequence_run_manager/src/sequence_run_manager_proc/tests/test_sequence_domain.py

* We will be still subscribing to ICA v1 ENS for BSSH event
* Our internal entity model as well as domain model are not specific to BSSH
* SequenceDomain struct wrap Sequence entity instance and its purpose is to
handle all translation between entity to domain event schema semantic
* EventBus schema auto-generated Code Bindings `sequencerunstatechange` is part
of domain package. Its internals should be interfaced through SequenceDomain
* Made a good unit test coverage on marshall/unmarshall and all aspect of serde
* Made `DJANGO_SETTINGS_MODULE` config mandatory instead of defaulting to base
* Added documentation

Implemented Sequence Run Manager BSSH event processing

---

docs/developer/FM.md
lib/workload/stateful/filemanager/Cargo.lock
lib/workload/stateful/filemanager/README.md
lib/workload/stateful/filemanager/deploy/README.md
lib/workload/stateful/filemanager/deploy/cdk.json
lib/workload/stateful/filemanager/deploy/package-lock.json
lib/workload/stateful/filemanager/deploy/package.json
lib/workload/stateful/filemanager/deploy/stack/filemanager_stack.ts
lib/workload/stateful/filemanager/deploy/stack/stack.ts
lib/workload/stateful/filemanager/docker-compose.yml
lib/workload/stateful/filemanager/filemanager-http-lambda/src/main.rs
lib/workload/stateful/filemanager/filemanager-ingest-lambda/Cargo.toml
lib/workload/stateful/filemanager/filemanager/Cargo.toml
lib/workload/stateful/filemanager/filemanager/src/events/s3/collect.rs
lib/workload/stateful/filemanager/filemanager/src/events/s3/mod.rs
lib/workload/stateful/filemanager/filemanager/src/events/s3/s3_client.rs
lib/workload/stateful/filemanager/scripts/deploy.sh
lib/workload/stateful/filemanager/scripts/logs.sh
lib/workload/stateful/filemanager/scripts/watch.sh

This PR aims at a LocalStack-less, AWS-deployable filemanager meso-service (since it's stateful w/ database et al).
Goal for this getting merged is Victor being able to deploy/operate/develop on it from the get-go, without local errors.
Will fix issues: #70 #71  ... at least

Filemanager: fix ingestion/deployment

---

config/constants.ts
lib/workload/orcabus-stateful-stack.ts
lib/workload/orcabus-stateless-stack.ts
lib/workload/stateful/database/component.ts
lib/workload/stateful/securitygroup/component.ts
test/workload/stateful/databaseConstruct.test.ts

Mainly the switch from `mysql` to `postgres` RDS

Update RDS Construct

---

lib/workload/stateful/event_source/component.ts
test/stateful/eventSourceConstruct.test.ts

Closes #111 
* Convert `EventSource` name rule to array.

fix: event source name rule should be an array

---

config/constants.ts
lib/workload/orcabus-stateless-stack.ts

fix: queue service name and secret name

---

lib/workload/stateless/filemanager/database/migrations/0002_add_s3_object_table.sql
lib/workload/stateless/filemanager/database/queries/ingester/aws/update_reordered_for_created.sql
lib/workload/stateless/filemanager/database/queries/ingester/aws/update_reordered_for_deleted.sql
lib/workload/stateless/filemanager/filemanager/src/database/aws/ingester.rs
lib/workload/stateless/filemanager/filemanager/src/events/aws/mod.rs
lib/workload/stateless/filemanager/filemanager/src/handlers/aws.rs

Closes #122 
* Correctly deals with null values in `version_id` when ingesting, reordering and detecting duplicates. Got to be careful of null comparisons in postgres :smiley_cat:.
* New tests for this case.

fix(filemanager): correctly deal with null version_id

---

config/constants.ts
lib/workload/orcabus-stateless-stack.ts
lib/workload/stateless/postgres_manager/construct/postgresManager.ts
lib/workload/stateless/postgres_manager/deploy/postgres-manager-stack.ts
lib/workload/stateless/postgres_manager/function/alter-pg-db-owner.ts
lib/workload/stateless/postgres_manager/function/create-pg-db.ts
lib/workload/stateless/postgres_manager/function/create-pg-iam-role.ts
lib/workload/stateless/postgres_manager/function/create-pg-login-role.ts
lib/workload/stateless/postgres_manager/function/type.ts
lib/workload/stateless/postgres_manager/function/utils.ts
lib/workload/stateless/postgres_manager/package.json
test/stateless/stateless-deployment.test.ts
tsconfig.json

- fix failing unit-test for postgres manager
- add cdk-nag supression
- ignore `tsc` check on microservice
- promote postgres-manager microservice from `cdk.construct` to `cdk.stack`

fix(postgres-manager): failing unit test from `cdk-nag`

---

lib/workload/stateless/filemanager/database/migrations/0002_add_s3_object_table.sql
lib/workload/stateless/filemanager/database/queries/ingester/aws/update_reordered_for_created.sql
lib/workload/stateless/filemanager/database/queries/ingester/aws/update_reordered_for_deleted.sql
lib/workload/stateless/filemanager/filemanager/src/database/aws/ingester.rs
lib/workload/stateless/filemanager/filemanager/src/events/aws/message.rs
lib/workload/stateless/filemanager/filemanager/src/events/aws/mod.rs
lib/workload/stateless/filemanager/filemanager/src/handlers/aws.rs

Closes #131 
* Make `version_id` required with a default value as the 'null' string.
* Ensure that only one row is returned from the main `current_objects` select query when reordering events.
* Various test fixes:
* Add tests for missing created/deleted events, missing sequencer values, and multiple matching rows for reordering.
* Fix permutation tests and add smaller non-ignored tests.

fix(filemanager): ingest constraints

---

lib/workload/stateless/postgres_manager/README.md
lib/workload/stateless/postgres_manager/function/create-pg-login-role.ts

- Modify the credential name for microservice secret 
from `orcabus/microservice/${microserviceName}` to `orcabus/${microserviceName}/RdsLoginCredential` - i think the name makes more sense to what it is used for, as each microservice might have its own secret

Postgres Manager Enhancement

---

lib/pipeline/orcabus-stateless-pipeline-stack.ts

Fixes #153
* Add Rust back to pipeline in order to run unit tests.
Potentially another way around this is to dockerize the unit tests? Although not sure if something like that is necessary.

fix(pipeline): install Rust for unit tests

---

lib/pipeline/orcabus-stateless-pipeline-stack.ts
lib/workload/stateless/filemanager/deploy/constructs/functions/function.ts

Related to #154.
* Reverts changes made in #152 to build filemanager outside of a docker container.
This removes the containerized filemanager build because the build container is unable to connect to host.docker.internal inside CodeBuild to check queries. I'll have to change the compose/docker networking settings in order to re-enable to containerized build. I've tested this is dev, so for now, this should hopefully allow the build to succeed :crossed_fingers:.

fix: pipeline error caused by filemanager containerized build

---

lib/workload/stateless/sequence_run_manager/deploy/component.ts

Fixed deployment by removing sequence_run_manager HttpStage

---

lib/workload/stateless/filemanager/database/Dockerfile
shared/mock-db.yml

* Bumps postgres versions to match RDS and fetch from public.ecr.aws.

build(deps): bump postgres versions to match RDS instance

---

.gitignore
lib/workload/stateless/sequence_run_manager/.coveragerc
lib/workload/stateless/sequence_run_manager/Makefile
lib/workload/stateless/sequence_run_manager/README.md
lib/workload/stateless/sequence_run_manager/deps/requirements-dev.txt
lib/workload/stateless/sequence_run_manager/deps/requirements-test.txt
lib/workload/stateless/sequence_run_manager/sequence_run_manager/tests/test_viewsets.py

* Improved SRM unit testing regime, coverage report
Related #139

Fixed sequence_run_manager endpoint unit test

---

config/constants.ts
lib/workload/components/cdk_resource_invoke.ts
lib/workload/orcabus-stateless-stack.ts
lib/workload/stateful/event_source/component.ts
lib/workload/stateless/filemanager/Cargo.lock
lib/workload/stateless/filemanager/Cargo.toml
lib/workload/stateless/filemanager/deploy/constructs/functions/function.ts
lib/workload/stateless/filemanager/deploy/constructs/functions/ingest.ts
lib/workload/stateless/filemanager/deploy/lib/filemanager.ts
lib/workload/stateless/filemanager/filemanager-http-lambda/Cargo.toml
lib/workload/stateless/filemanager/filemanager-ingest-lambda/Cargo.toml
lib/workload/stateless/filemanager/filemanager-migrate-lambda/Cargo.toml
lib/workload/stateless/filemanager/filemanager/Cargo.toml
lib/workload/stateless/filemanager/filemanager/src/env.rs
test/stateless/cdkResourceInvoke.test.ts
test/stateless/stateless-deployment.test.ts

Closes #169 
* As described in #169 except using `RDS_IAM` as part of postgres manager. Note, currently this still uses the master RDS credentials. Both these points will be addressed in #138.
* Move `CdkResourceInvoke` to `components`.
* Add stg and prod filemanager deployments.

refactor: filemanager stack

---

lib/workload/stateless/filemanager/Makefile
lib/workload/stateless/filemanager/compose.yml

Related to #180
* Fixes container name clash in CodeBuild by allowing docker to automatically name containers.

fix(filemanager): let docker decide on container names

---

lib/workload/stateless/filemanager/.env.example
lib/workload/stateless/filemanager/Makefile
lib/workload/stateless/filemanager/compose.yml
lib/workload/stateless/filemanager/deploy/constructs/functions/function.ts

Related to #180 and #183.
Not sure exactly why the CodeBuild docker error occurs, but I think it's something to do with running `docker compose` in parallel. E.g. try running `docker compose up & docker compose up` and the same error occurs.
Either way, to hopefully fix this for good, the changes are:
* Use `docker compose run` in the CDK code, which always creates a unique container name with a random suffix.
* Local dev can still use `docker compose up`.
* Use address and port `0.0.0.0:0` to create an arbitrary host:port mapping to the host.
* Rearrange `Makefile` and `.env.example` to reflect these changes.

fix(filemanager): use docker run to get unique containers

---

lib/workload/stateless/filemanager/Makefile
lib/workload/stateless/filemanager/deploy/constructs/functions/function.ts
package.json
yarn.lock

Related to #180, #183, #184 and #169.
Hopefully this is the last of these, this time making sure by running tests using local CodeBuild.

fix(filemanager): silence Makefile output and trim lines

---

lib/workload/stateless/filemanager/Cargo.lock
lib/workload/stateless/filemanager/deploy/constructs/functions/function.ts
lib/workload/stateless/filemanager/filemanager-http-lambda/Cargo.toml
lib/workload/stateless/filemanager/filemanager-ingest-lambda/Cargo.toml
lib/workload/stateless/filemanager/filemanager-migrate-lambda/Cargo.toml
lib/workload/stateless/filemanager/filemanager/Cargo.toml

Related to #169 and associated PRs.
100% this should work now.
* Add random uuid to target directory to prevent parallel execution of tests from interfering with another test's compiled outputs.
* Bump deps.
Thanks for the `codebuild-breakpoint` tip @victorskl, it helped a lot to find the issue.

fix(filemanager): add uuid to target directory to avoid concurrency errors

---

lib/workload/stateless/postgres_manager/deploy/postgres-manager-stack.ts
test/stateless/stateless-pipeline.test.ts

It seems that cdk-ing the pipeline stack will also synth all the children stacks (microservice stack), but we also have a dedicated test for these children stacks. The `cdk-nag` test only works on the top layer stack and for that reason we have the deployment (children) stack to be tested separately.
The solution is to mock the children stack with a mock stack when testing the pipeline so it doesn't expose the real micro-stack. This should half the building time for testing.
Thanks @mmalenic for pointing the double build when testing!

Update Stateless Pipeline Test

---

config/constants.ts
lib/workload/orcabus-stateless-stack.ts
lib/workload/stateful/database/component.ts
lib/workload/stateful/event_source/component.ts
lib/workload/stateless/filemanager/.gitignore
lib/workload/stateless/filemanager/Cargo.lock
lib/workload/stateless/filemanager/deploy/constructs/functions/function.ts
lib/workload/stateless/filemanager/deploy/constructs/functions/ingest.ts
lib/workload/stateless/filemanager/deploy/lib/filemanager.ts
lib/workload/stateless/filemanager/filemanager-http-lambda/src/main.rs
lib/workload/stateless/filemanager/filemanager-ingest-lambda/src/main.rs
lib/workload/stateless/filemanager/filemanager-migrate-lambda/src/main.rs
lib/workload/stateless/filemanager/filemanager/Cargo.toml
lib/workload/stateless/filemanager/filemanager/src/clients/aws/config.rs
lib/workload/stateless/filemanager/filemanager/src/clients/aws/s3.rs
lib/workload/stateless/filemanager/filemanager/src/clients/aws/sqs.rs
lib/workload/stateless/filemanager/filemanager/src/database/aws/credentials.rs
lib/workload/stateless/filemanager/filemanager/src/database/aws/ingester.rs
lib/workload/stateless/filemanager/filemanager/src/database/aws/migration.rs
lib/workload/stateless/filemanager/filemanager/src/database/aws/mod.rs
lib/workload/stateless/filemanager/filemanager/src/database/mod.rs
lib/workload/stateless/filemanager/filemanager/src/env.rs
lib/workload/stateless/filemanager/filemanager/src/error.rs
lib/workload/stateless/filemanager/filemanager/src/events/aws/collecter.rs
lib/workload/stateless/filemanager/filemanager/src/events/aws/message.rs
lib/workload/stateless/filemanager/filemanager/src/events/aws/mod.rs
lib/workload/stateless/filemanager/filemanager/src/handlers/aws.rs
lib/workload/stateless/filemanager/filemanager/src/uuid.rs
lib/workload/stateless/postgres_manager/deploy/postgres-manager-stack.ts
test/stateful/eventSourceConstruct.test.ts

Closes #138 
* Generate RDS IAM credentials in order to connect to the filemanager database.
* This uses `DbAuthType.RDS_IAM` postgres manager setting.
* Add a name to the event source dead letter queue.
* Filemanager lambda functions now use a shared database pool created in the init lambda execution phase.

feat(filemanager): iam rds credentials

---

config/constants.ts
lib/workload/stateful/database/component.ts
lib/workload/stateless/metadata_manager/app/settings/aws.py
lib/workload/stateless/metadata_manager/deploy/stack.ts
lib/workload/stateless/postgres_manager/README.md
lib/workload/stateless/postgres_manager/deploy/postgres-manager-stack.ts
lib/workload/stateless/postgres_manager/function/create-pg-login-role.ts
lib/workload/stateless/sequence_run_manager/deploy/component.ts
lib/workload/stateless/sequence_run_manager/sequence_run_manager/settings/aws.py
test/stateful/stateful-deployment.test.ts

- Make Master and µ-app secret manager to start rotating
- Secret Manager for µ-app is now in CDK instead of created from lambda
ToDo after merge:
- delete µ-app secret manager that is created outside cdk
closes #127

Rotatable Db Secret Manager

---

lib/workload/stateful/stacks/token-service/deploy/stack.ts

* It is better to align Service User secret in JSON
format container as initial value. Otherwise, JSON
parsing error could mis-lead the admin user who'd
reset this value as initial bootstrap step.

Fixed Token Service initial value json parsing

---

config/config.ts
config/constants.ts
config/stacks/fileManager.ts
config/stacks/icaEventPipe.ts
config/stacks/metadataManager.ts
config/stacks/postgresManager.ts
config/stacks/sequenceRunManager.ts
config/stacks/shared.ts
config/stacks/tokenService.ts
lib/pipeline/statefulPipelineStack.ts
lib/pipeline/statelessPipelineStack.ts
lib/workload/stateful/stacks/shared/constructs/database/index.ts
test/stateful/pipeline/deployment.test.ts
test/stateful/shared/computeConstruct.test.ts
test/stateful/shared/databaseConstruct.test.ts
test/stateful/shared/eventbusConstruct.test.ts
test/stateful/shared/schemaRegistryConstruct.test.ts
test/stateful/token-service/tokenServiceConstruct.test.ts
test/stateless/deployment.test.ts

Just the initial phase of refactoring config file as now seems to be a bit tedious. Splitting the config per individual stack, so could make use of the Type check for each stack props.
Partial #167

chore: splitting config file

---

lib/workload/stateless/stacks/filemanager/deploy/constructs/functions/function.ts

When building the rust function, it wants to connect to the file manager, because I'm working on a intel machine, this needs to be built over a docker container, when doing so it doesn't by default allow ports on the container, and then fails as it can't find the existing docker container running the file manager. 
Resolves #241

Fix docker options for filemanager

---

lib/workload/stateful/stacks/shared/constructs/event-bus/custom-event-archiver/archive_service/universal_event_archiver.py
lib/workload/stateful/stacks/shared/constructs/event-bus/index.ts
test/stateful/pipeline/deployment.test.ts

1. Fix #244 
fix logger info format error in lambda
Duplicate Event Reason:
From the cloud watch log about this func, we have error in `logger.info` , and the error is```Error storing event: not all arguments converted during string formatting```, this may come the `%s` is a placeholder that expects a string to replace in the info.
And this error will trigger retry function in our setting. Retry 3 times will generate 3 copy of the events.
2. Fix #245 
As I check around for our could trail events, we may not need the to retain the server access logs for event archiver bucket, as the main purpose for this bucket is to "**archive**" already, and serve for event statistic and analysis.
PS: add cdk-nag Suppressions for unit testing error for the s3 bucket: 
`["AwsSolutions-S1: The S3 Bucket …

Fix event duplication And Remove Server access logs when archiving to bucket 

---

Makefile

Error on PostgresManager install will disable this so pipeline could run back.

Disable Postgres Manager 

---

config/config.ts
config/constants.ts
config/stacks/shared.ts
lib/workload/stateful/stacks/shared/constructs/event-bus/index.ts

Fix/Refactor of event archiver: 
1. RemovalPolicy:
`RemovalPolicy.DESTROY `mode in our dev/test envs, 
only enable `RemovalPolicy.RETAIN` in prod env. 
For dev/test redeployment, we may still delete all contents in the bucket and get the bucket physically deleted.
2. unique bucket name 
beta: orcabus-event-archive-_`devAccountId`_, 
gamma: orcabus-event-archive-_`stgAccountId`_, 
prod: orcabus-event-archive-_`prodAccountId`_, 
From discuss: https://umccr.slack.com/archives/C03ABJTSN7J/p1713927722151309

event archive bucket policy modification according different env

---

config/stacks/shared.ts
lib/workload/stateful/stacks/shared/constructs/event-bus/index.ts
test/stateful/shared/eventbusConstruct.test.ts

for custom  event bus archiver:
1. refactor current event bus archiver props with new `EventBusArchiverProps` for **clarity and granular manipulation**, and also enable eventbus props for future extension with more special archivers.
2. fixing stateful unit testing error with new name conventions in` eventbusConstruct.test.ts`

custom event bus archiver props and stateful unit testing fixing

---

lib/workload/stateless/stacks/cttso-v2-pipeline-manager/deploy/constructs/cttsov2-icav2-manager/index.ts

Related issue: https://github.com/aws/aws-cdk/issues/20177
`grantInvoke` will use `*` for all lambda versions which breaks cdk-nag.  
By using `currentVersion` attribute of the lambda obj we only grantInvoke for only the latest version of the lambda object, resolving the cdc-nag errors

Use 'currentVersion' for lambda object to resolve the cdk nag issue

---

docs/event-schemas/wfm/WorkflowRunStateChange.json

* The `serviceVersion` field get refactored into Payload version
Hence, it is obsolete property. It was oversight to remove it
from previous PR #272.
Related #257

Fixed WorkflowRunStateChange schema required field

---

.github/workflows/prbuild.yml
README.md
lib/pipeline/statelessPipelineStack.ts
test/stateless/pipeline.test.ts

Put back GH Action which runs on AWS CodeBuild as GH Runners except for lint and Security check. All application test runs at different CodeBuild runner to cut on time.

feat: Refine Testing Configuration

---

config/stacks/icav2EventTranslator.ts
lib/workload/stateless/stacks/icav2-event-translator/deploy/stack.ts

fix this [build](https://ap-southeast-2.console.aws.amazon.com/codesuite/codepipeline/pipelines/OrcaBusStatelessPipeline-Pipeline9850B417-195F6QW8HU9NP/view?region=ap-southeast-2) issue:
1. add namespace in the ica event translator lambdaSecurityGroupName
2. create a new SG group with the lambdaSecurityGroupName
PS: Build Error come from `No security groups found matching`.

Fix ica event translator build issue

---

README.md
docs/event-schemas/README.md

* Improved repo landing README.md

Added documentation on Event Schema and Namespace guide

---

lib/workload/stateless/stacks/workflow-manager/deps/requirements.txt

Fixes to large lambda layer by removing unnecessary transient libs from libumccr.

Update libumccr version to 0.4.0rc3

---

lib/workload/stateless/stacks/workflow-manager/deploy/stack.ts
lib/workload/stateless/stacks/workflow-manager/workflow_manager/models/workflow_run.py
lib/workload/stateless/stacks/workflow-manager/workflow_manager_proc/lambdas/handle_service_wrsc_event.py
lib/workload/stateless/stacks/workflow-manager/workflow_manager_proc/lambdas/transition_bcm_fastq_copy.py
lib/workload/stateless/stacks/workflow-manager/workflow_manager_proc/services/create_workflow_run.py
lib/workload/stateless/stacks/workflow-manager/workflow_manager_proc/services/emit_workflow_run_state_change.py
lib/workload/stateless/stacks/workflow-manager/workflow_manager_proc/services/get_workflow_run.py

Fix the following:
- correct call to handler methods
- unmarshaller usage.
- workflow type/name legacy code
- datetime handling
- handle non-existing `Workflow` record when persisting `WorkflowRun` record

Fix workflow manager issues when handling WRSC events

---

config/constants.ts

Resolves https://github.com/umccr/orcabus/issues/339
Note that the aws secret `/manual/BaseSpaceAccessTokenSecret` will need to change (just before we merge this PR), from the trial secret to the dev secret in order for BCLs to transfer to the BSSH dev account

Move from trial project to dev project for umccr-development account

---

config/constants.ts
config/stacks/bsRunsUploadManager.ts
lib/workload/stateless/stacks/bs-runs-upload-manager/deploy/constructs/bs-runs-upload-manager/index.ts
lib/workload/stateless/stacks/bs-runs-upload-manager/deploy/stack.ts
lib/workload/stateless/stacks/bs-runs-upload-manager/lambdas/upload_v2_samplesheet_to_gds_bssh/handler.py
lib/workload/stateless/stacks/bs-runs-upload-manager/layers/src/bs_runs_upload_manager_tools/utils/portal_helpers.py
lib/workload/stateless/stacks/bs-runs-upload-manager/layers/src/bs_runs_upload_manager_tools/utils/samplesheet_helpers.py

Resolves error where requests expects env var to be url instead of a domain

Convert api-url to api-domain

---

lib/workload/components/dynamodb-icav2-handle-event-change-sfn/index.ts

We cannot rely on the pipeline ID (since a user might want a different pipeline id to be run), 
We cannot rely on the pipeline Code (since ctDNA Pipeline codes are inconsistent between versions)
Instead the workflow run name (or userRefence) generated will always be `umccr_automated__${workflow_name}`.
Resolves #344 
Can confirm this works by using an eventSandbox

User reference will always start with 'umccr__automated__workflowName`

---

lib/workload/stateless/stacks/bs-runs-upload-manager/Readme.md
lib/workload/stateless/stacks/bs-runs-upload-manager/deploy/constructs/bs-runs-upload-manager/index.ts

* Updated from `orcabus.srm` to `orcabus.sequencerunmanager`
* Updated equals-ignore-case filter expression to Sequence status `SUCCEEDED`

Updated BasespaceRunsUploadManager event rule with SequenceRunManager convention

---

config/constants.ts
config/stacks/fileManager.ts
lib/workload/components/named-lambda-role/index.ts
lib/workload/stateless/stacks/filemanager/deploy/constructs/functions/function.ts
lib/workload/stateless/stacks/filemanager/deploy/constructs/functions/ingest.ts
lib/workload/stateless/stacks/filemanager/deploy/constructs/functions/inventory.ts
lib/workload/stateless/stacks/filemanager/deploy/stack.ts
lib/workload/stateless/stacks/filemanager/filemanager/src/error.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/events/aws/collecter.rs
test/stateless/deployment.test.ts

Closes #354 
* Makes the `HeadObject` call for ingesting events optional.

fix(filemanager): make `HeadObject` optional

---

Makefile

```
% make clean
find: ./lib/workload/stateless/layers: No such file or directory
```

Remove wrongly commented clean target

---

lib/workload/components/dynamodb-icav2-handle-event-change-sfn/step_functions_templates/icav2_get_workflow_status_and_raise_internal_event.asl.json
lib/workload/components/dynamodb-icav2-ready-event-handler-sfn/step_functions_templates/icav2_launch_workflow_and_raise_internal_event.asl.json

* Payload `refId` is no longer required for Execution Services
* Payload data should wrap under `data` property

Fixed ICAv2 event handle StepFunction Payload schema

---

lib/workload/components/dynamodb-icav2-handle-event-change-sfn/index.ts

* This has to be in-synced with ICAv2 workflow trigger side convention

Fixed ICAv2 event rule prefix matching

---

lib/workload/stateful/stacks/token-service/token_service/rotate_service_jwt.py

* Follow AWS guide by validating against current UTC time
to token expire time. Threshold set to 22 hour to give
a bit of headroom with rotation scheduler. i.e. If JWT
has > 22 hours lifetime, it is valid.

Fixed Token Service JWT validation logic

---

cdk.context.json
lib/pipeline/statefulPipelineStack.ts
lib/workload/components/api-gateway/index.ts

- Comment out Prod stage in stateful pipeline, SG lookup will fail when doesn't exist. SG lookup is needed by the pg-manager
- Move SSM Parameter lookup to resolve result on deployment
- Update `context.json`

Fix: STG Deployment

---

lib/workload/stateless/stacks/filemanager/filemanager/src/database/mod.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/handlers/aws.rs

This should fix the failed deployment from #372.
Closes  #315.
* Create a `PgPool` first and then a `DatabaseConnection` to avoid a bug in `to_url_lossy` with `sslmode`.

fix(filemanager): avoid using to_url_lossy when loading database credentials

---

lib/workload/stateless/stacks/workflow-manager/deploy/stack.ts

* Suppressed with `@ts-ignore` for now as EventBridge able to accept the rule syntax.
See https://github.com/aws/aws-cdk/issues/30220

Fixed WorkflowManager event rule syntax

---

lib/workload/stateless/stacks/filemanager/Cargo.lock
lib/workload/stateless/stacks/filemanager/database/migrations/0003_add_sequencer_index.sql
lib/workload/stateless/stacks/filemanager/filemanager/Cargo.toml
lib/workload/stateless/stacks/filemanager/filemanager/src/queries/list.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/queries/mod.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/routes/list.rs

Closes #395 
* Order by sequencer in list API queries.
* Add an index on the sequencer to support better sorting of ingested events.
* I think this effectively does what this piece of code is doing, except it's a native construct to the database: https://github.com/umccr/orcabus/blob/2e4772c22edf982aef7d64fc4b10c685a716433c/lib/workload/stateless/stacks/filemanager/database/queries/ingester/aws/update_reordered_for_created.sql#L64-L90 This is one of the reasons why I simplified the database ingestion, because I think a similar trade off with ingest/query performance can be achieved by just using an index (although I would need to test this to be sure).

fix(filemanager): sequencer ordering

---

lib/workload/stateless/stacks/filemanager/filemanager/src/database/aws/ingester.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/database/aws/ingester_paired.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/events/aws/inventory.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/events/aws/message.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/events/aws/mod.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/handlers/aws.rs

Fixes #397 
Turns out that e_tags [should be double quoted](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag) to distinguish between two different kinds of e_tags, weak and strong. An e_tag is quoted when received from an SDK `HeadObjectOutput`. However, EventBridge/SQS sends S3 events with unquoted e_tags, resulting in a mismatch when ingesting events.
* Check/modify all e_tags to ensure that they are quoted before ingesting events.
* Move the `default_version_id` to `messages.rs`.

fix: filemanager e_tag quoting

---

lib/workload/stateless/stacks/filemanager/Cargo.lock
lib/workload/stateless/stacks/filemanager/filemanager/Cargo.toml
lib/workload/stateless/stacks/filemanager/filemanager/src/queries/get.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/queries/list.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/queries/mod.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/routes/filtering.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/routes/get.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/routes/list.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/routes/mod.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/routes/openapi.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/routes/pagination.rs

Closes #407 
* Adds query parameter filtering on most columns for list operations on objects.
* Adds JSON contains operation for attributes which can be accessed using nested notation, e.g: `attributes[attribute_id]=id`.
* This uses https://github.com/samscott89/serde_qs and has similar syntax to https://github.com/ljharb/qs.
* Move `Pagination` to its own module to avoid a large `list.rs` file.
* Refactor tests to reduce code duplication.

feat: filemanager filter query parameters

---

lib/workload/stateless/stacks/filemanager/filemanager/src/queries/list.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/queries/mod.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/routes/list.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/routes/pagination.rs

Closes #414 
* Add `current_state` query and API parameter.
* Add some missing tests and allow `/s3_object/count`/`object/count` requests to use filtering and the `current_state` query parameters

feat: filemanager current state

---

lib/workload/stateless/stacks/metadata-manager/app/models/base.py
lib/workload/stateless/stacks/metadata-manager/app/serializers.py
lib/workload/stateless/stacks/metadata-manager/app/settings/base.py
lib/workload/stateless/stacks/metadata-manager/app/settings/local.py
lib/workload/stateless/stacks/metadata-manager/app/tests/test_viewsets.py
lib/workload/stateless/stacks/metadata-manager/app/viewsets/lab.py

Add additional API to view records extensively with their link models. The main use case is for UI purposes.
- `/subject/full/`
this also supports filters from the library Id (by using the query `?library_internal_id=L000`), perhaps this might be useful to see related library pairs.
```
results:
{
"id": 100,
"specimen_set": [
{
"id": 101,
"library_set": [
{
"id": 1625,
"internal_id": "L0001",
...
"specimen": 101
}
],
"internal_id": "SPC0001",
...
"subject": 100
}
],
"internal_id": "SBJ0001"
}
```
- `/library/full/`
```
results:
{
"id": 1000,
"specimen": {
"id": 1000,
"subject": {
"id": 1000,
"internal_id": "SBJ0001"
},
"internal_id": "SPC001",
},
"internal_id": "L001",
...
}
```

Feature(metadata-manager): Additional API

---

lib/workload/stateless/stacks/filemanager/Cargo.lock
lib/workload/stateless/stacks/filemanager/Makefile
lib/workload/stateless/stacks/filemanager/README.md
lib/workload/stateless/stacks/filemanager/filemanager-api-server/Cargo.toml
lib/workload/stateless/stacks/filemanager/filemanager-api-server/src/main.rs
lib/workload/stateless/stacks/filemanager/filemanager/Cargo.toml
lib/workload/stateless/stacks/filemanager/filemanager/src/database/aws/credentials.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/env.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/queries/get.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/queries/list.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/queries/mod.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/routes/get.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/routes/list.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/routes/pagination.rs

Closes #417 
* Add database loading and mocking command line options to the `filemanager-api-server`.
This is basically is just re-using the data generation component I had for testing [here](https://github.com/umccr/orcabus/blob/6d0bc9068fbe666bc1eaf2a6b9dc46afe47d94be/lib/workload/stateless/stacks/filemanager/filemanager/src/queries/mod.rs#L111-L115), except with a bit of a tidy of the function API/interface.

feat(filemanager): add database mocking to local API server

---

lib/workload/stateless/stacks/filemanager/Cargo.lock
lib/workload/stateless/stacks/filemanager/filemanager-api-lambda/Cargo.toml
lib/workload/stateless/stacks/filemanager/filemanager-api-lambda/src/main.rs
lib/workload/stateless/stacks/filemanager/filemanager-ingest-lambda/Cargo.toml
lib/workload/stateless/stacks/filemanager/filemanager-inventory-lambda/Cargo.toml
lib/workload/stateless/stacks/filemanager/filemanager-migrate-lambda/Cargo.toml
lib/workload/stateless/stacks/filemanager/filemanager/Cargo.toml
lib/workload/stateless/stacks/filemanager/filemanager/src/env.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/error.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/handlers/aws.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/handlers/mod.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/queries/get.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/queries/list.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/queries/mod.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/queries/update.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/routes/attributes.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/routes/error.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/routes/get.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/routes/ingest.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/routes/list.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/routes/mod.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/routes/openapi.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/routes/pagination.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/routes/update.rs

Closes #423 
* Adds multiple PATCH routes which allow updating the attributes column for a single `s3_object`/`object`, or a collection of records.
* This uses JSON patch to perform the update by first querying the database for the correct records to update, then applying the patch to the attributes column, and writing the attributes back to the database.
* Add tests for the new endpoints and update the openapi docs.
* Return `NOT_FOUND` for getting/updating single records if the supplied `id` does not exist.
* Bump a few dependencies.
This is part of the change that allows attribute linking. In theory, any service can now add whatever attributes they want to a filemanager record. Still to do is implementing a rule system to submit jobs for linking attributes on filemanager records, and …

feat(filemanager): attribute updating API

---

Makefile
lib/workload/stateless/stacks/metadata-manager/app/settings/local.py
lib/workload/stateless/stacks/metadata-manager/app/urls/local.py
lib/workload/stateless/stacks/metadata-manager/deps/requirements-dev.txt
lib/workload/stateless/stacks/metadata-manager/deps/requirements-slim.txt
lib/workload/stateless/stacks/sequence-run-manager/deps/requirements-dev.txt
lib/workload/stateless/stacks/sequence-run-manager/deps/requirements.txt
lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/pagination.py
lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/settings/base.py
lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/settings/local.py
lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/urls/base.py
lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/urls/local.py
lib/workload/stateless/stacks/workflow-manager/deps/requirements-dev.txt
lib/workload/stateless/stacks/workflow-manager/deps/requirements.txt
lib/workload/stateless/stacks/workflow-manager/workflow_manager/pagination.py
lib/workload/stateless/stacks/workflow-manager/workflow_manager/settings/base.py
lib/workload/stateless/stacks/workflow-manager/workflow_manager/settings/local.py
lib/workload/stateless/stacks/workflow-manager/workflow_manager/urls/base.py
lib/workload/stateless/stacks/workflow-manager/workflow_manager/urls/local.py

Upgrade OpenAPI to V3 for Django microservice (SRM, WFM, MM). Replaces the [drf_yasg](https://drf-yasg.readthedocs.io/en/stable/) with [drf-spectacular](https://drf-spectacular.readthedocs.io/en/latest/).
Note: [The Built-in OpenAPI generator from the Django Rest framework is deprecated.](https://www.django-rest-framework.org/topics/documenting-your-api/#built-in-openapi-schema-generation-deprecated)

Chore: Upgrade OpenAPI3 for DRF Microservice

---

Makefile
README.md
compose.yml
lib/workload/stateless/stacks/filemanager/.dockerignore
lib/workload/stateless/stacks/filemanager/.env.example
lib/workload/stateless/stacks/filemanager/.gitignore
lib/workload/stateless/stacks/filemanager/Dockerfile
lib/workload/stateless/stacks/filemanager/Makefile
lib/workload/stateless/stacks/filemanager/compose.yml
lib/workload/stateless/stacks/filemanager/filemanager-api-server/Cargo.toml
lib/workload/stateless/stacks/filemanager/filemanager-api-server/src/main.rs

Following up from #425
* Add Dockerfile for building filemanager.
* Add filemanager to the local microservices setup from the top-level directory.
* This loads the most recent 100000 records from the dev database. 
* Fix env variable parsing for `filemanager-api-server`.
This was a bit tougher than I expected. One of the problems is that the filemanager relies on having access to a database to generate code for types/schemas at compile time. This is challenging in a Docker context, because the build process is not run in the compose network, and there is no straightforward way to have a database running before building the filemanager Dockerfile.
In the future, I think I might remove the compile-time database requirement from filemanager. It seems like it often gets in the way, and tools …

fix: add filemanager to local API setup

---

lib/workload/stateless/stacks/filemanager/Dockerfile
lib/workload/stateless/stacks/filemanager/filemanager/Cargo.toml

This is in relation to #429.
* Fixes the Dockerfile definition which was caching dependency compilations for a debug target, when the main filemanager build was release.
* All targets now use debug.
* This halved my compilation times because now things aren't compiling twice accidentally.
Initially I had this compiling release because of embedded files in swagger UI: https://github.com/juhaku/utoipa?tab=readme-ov-file#swagger-ui-returns-404-notfound-from-built-binary. Instead, it's now compiling as debug with the `debug-embed` flag enabled for `utoipa-swagger-ui`, which should be faster.

fix(filemanager): Dockerfile caching layer and debug build

---

lib/workload/stateless/stacks/sequence-run-manager/deploy/stack.ts

* Configured processing Lambda to `reservedConcurrentExecutions` to 1. We have
time upto minutes to process basespace events. No hurries.

Updated SRM processing to Singleton Lambda pattern

---

docs/developer/DJANGO_API.md
skel/django-api/README.md
skel/django-api/compose.yml
skel/django-api/deps/requirements-dev.txt
skel/django-api/deps/requirements-test.txt
skel/django-api/deps/requirements.txt
skel/django-api/project_name/pagination.py
skel/django-api/project_name/settings/base.py
skel/django-api/project_name/settings/local.py
skel/django-api/project_name/urls/base.py
skel/django-api/project_name/urls/local.py

* Replaced drf_yasg with drf_spectacular
* Removed version pinning as skel template

Improved Django skel template

---

lib/workload/stateless/stacks/filemanager/README.md
lib/workload/stateless/stacks/filemanager/deploy/constructs/functions/function.ts
lib/workload/stateless/stacks/filemanager/docs/API_GUIDE.md
lib/workload/stateless/stacks/filemanager/docs/ATTRIBUTE_LINKING.md
lib/workload/stateless/stacks/filemanager/filemanager-api-server/README.md
lib/workload/stateless/stacks/filemanager/filemanager/src/error.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/queries/list.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/queries/update.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/routes/error.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/routes/filter/mod.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/routes/filter/wildcard.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/routes/list.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/routes/mod.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/routes/openapi.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/routes/update.rs

Closes #456
* Add wildcard matching to API routes for list/update.
* Wildcards use '%' for multiple characters and '_' for single characters, which get converted to `like` queries.
* `case_sensitive` can be used to control whether the query is `like` or `ilike`.
* Wildcards are also supported in JSON attributes.
* Add API guide and design docs.
* Update tests and OpenAPI definitions.

feat: filemanager API wildcards

---

lib/workload/stateless/stacks/filemanager/Makefile

Related to #464
* Fix `Makefile` so that it does not use `object` data dumps when loading from s3.
* Data dump has been updated on S3.

fix(filemanager): local s3-load should not use `object`

---

compose.yml
lib/workload/stateless/stacks/filemanager/compose.yml
lib/workload/stateless/stacks/filemanager/docs/API_GUIDE.md
lib/workload/stateless/stacks/filemanager/filemanager-api-lambda/src/main.rs
lib/workload/stateless/stacks/filemanager/filemanager-api-server/src/main.rs
lib/workload/stateless/stacks/filemanager/filemanager/Cargo.toml
lib/workload/stateless/stacks/filemanager/filemanager/src/clients/aws/s3.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/database/aws/credentials.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/env.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/error.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/queries/get.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/queries/list.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/queries/update.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/routes/error.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/routes/filter/mod.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/routes/get.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/routes/ingest.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/routes/list.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/routes/mod.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/routes/openapi.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/routes/pagination.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/routes/presign.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/routes/update.rs

Closes #459
* Adds routes under `/s3/presign` and `/s3/presign/{:id}` to fetch presigned URLs for current objects only.
* `responseContentDisposition` can be used to set the content-disposition of the presigned `GetObject` request. The default value is `inline`, as this matches the HTTP `content-disposition` header.

feat: filemanager presigned route

---

lib/workload/stateless/stacks/filemanager/database/migrations/0005_rename_date.sql
lib/workload/stateless/stacks/filemanager/database/queries/api/select_existing_by_bucket_key.sql
lib/workload/stateless/stacks/filemanager/database/queries/api/select_object_ids.sql
lib/workload/stateless/stacks/filemanager/database/queries/ingester/aws/insert_s3_created_objects.sql
lib/workload/stateless/stacks/filemanager/database/queries/ingester/aws/insert_s3_objects.sql
lib/workload/stateless/stacks/filemanager/database/queries/ingester/aws/update_reordered_for_created.sql
lib/workload/stateless/stacks/filemanager/docs/API_GUIDE.md
lib/workload/stateless/stacks/filemanager/filemanager/src/database/aws/ingester.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/database/aws/ingester_paired.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/database/aws/query.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/database/mod.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/queries/list.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/queries/mod.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/queries/update.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/routes/filter/mod.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/routes/update.rs

Some more misc changed, related to #462
* JSON patch now supports append only, so "add", "test", or "copy" only if an existing key is not being overwritten.
* The outer "attributes" on patch requests is not required.
* `date` has been renamed to `eventTime` for more clarity. /cc @williamputraintan 
I'm holding off on implementing the shortened attributes query string feature, e.g. `portal_run_id=...` rather than `attributes[portal_run_id]=...` as described in #462. This is slightly more complex as it involves capturing unknown parameters in the API. I'm not sure if this is the best idea, because it has the potential to conflict with existing parameters.

refactor(filemanager): misc simpler and clearer API

---

compose.yml
lib/workload/stateless/stacks/filemanager/Makefile
lib/workload/stateless/stacks/filemanager/compose.yml
lib/workload/stateless/stacks/filemanager/deploy/constructs/functions/api.ts
lib/workload/stateless/stacks/filemanager/deploy/constructs/functions/ingest.ts
lib/workload/stateless/stacks/filemanager/deploy/stack.ts
lib/workload/stateless/stacks/filemanager/filemanager/src/clients/aws/s3.rs

Related to #459 
* Fix presigned URL route so that URLs can be accessed. The fix is two-fold:
* The API function needs `GetObject` access to the buckets.
* Checksum mode should not be used because this creates an additional header `x-amz-checksum-mode` which is supposed to be present when fetching the presigned URL.
* Adjust `Makefile` so that finding a postgres database behaves nicer with the top-level `make start-all-service`.

fix(filemanager): presigned URL access

---

docs/schemas/events/executionservice/WorkflowRunStateChange.schema.json
docs/schemas/events/executionservice/example/WRSC__example1.json
docs/schemas/events/workflowmanager/WorkflowRunStateChange.schema.json
docs/schemas/events/workflowmanager/example/WRSC__example1.json

This is a new convention to support the linking of workflow runs to libraries.
The association currently has to be supported by the execution services / stacky glues that have that information, as the workflow manager does not have access to it atm.
Also, the workflow manager currently relies on the WRSC event to establish the library association, including the `libraryId` (from the lab metadata) and the corresponding `orcabusId` (from the metadata manager). This is expected to be relaxed once we have a different mechanism of updating the workflow manager (e.g. `LibraryStateChange` events).
@raylrui @williamputraintan 
For now this addition is optional as to not break any existing implementations. However, it would be great if we could adopt this wherever possible.

Add support for linked libraries to WRSC event schema

---

config/constants.ts
config/stacks/stackyMcStackFace.ts
lib/workload/stateful/stacks/stacky-mcstackface-dynamodb/index.ts
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/index.ts
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/loctite/part_5/library-qc-complete-db-to-tn-draft/lambdas/generate_draft_event_payload_py/generate_draft_event_payload.py
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/loctite/part_5/library-qc-complete-db-to-tn-draft/step_functions_templates/add_library_qc_complete_to_tn_draft_sfn_template.asl.json
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/mod-podge/part_4/library-qc-complete-to-wts-draft/lambdas/generate_draft_event_payload_py/generate_draft_event_payload.py
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/mod-podge/part_4/library-qc-complete-to-wts-draft/step_functions_templates/add_library_qc_complete_to_wts_draft_sfn_template.asl.json
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/pva/index.ts
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/pva/part_1/initialise-umccrise-subject-dbs/index.ts
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/pva/part_1/initialise-umccrise-subject-dbs/step_functions_templates/initialise_umccrise_subject_db_sfn_template.asl.json
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/pva/part_2/initialise-umccrise-library-dbs/index.ts
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/pva/part_2/initialise-umccrise-library-dbs/step_functions_templates/initialise_umccrise_library_db_sfn_template.asl.json
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/pva/part_3/update-fastq-list-rows-dbs/index.ts
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/pva/part_3/update-fastq-list-rows-dbs/step_functions_templates/add_fastq_list_rows_db_sfn_template.asl.json
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/pva/part_4/tn-complete-to-umccrise-draft/index.ts
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/pva/part_4/tn-complete-to-umccrise-draft/lambdas/generate_draft_event_payload_py/generate_draft_event_payload.py
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/pva/part_4/tn-complete-to-umccrise-draft/step_functions_templates/tn_complete_to_umccrise_draft_sfn_template.asl.json
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/pva/part_5/umccrise-draft-to-ready/index.ts

Added the stateful umccrise stacky database
Added the logic parts for generating a umccrise ready event
Easier to merge this now knowing at least the umccrise stateful db will be created and there won't be conflicts if I redeploy locally.

Stacky updates for generating umccrise events

---

lib/workload/components/python-metadata-tools-layer/metadata_tools_layer/src/metadata_tools/utils/library_helpers.py
lib/workload/components/python-metadata-tools-layer/metadata_tools_layer/src/metadata_tools/utils/specimen_helpers.py
lib/workload/components/python-metadata-tools-layer/metadata_tools_layer/src/metadata_tools/utils/subject_helpers.py

Used by the stacky shower events to query library information

Use the new metadata library endpoint for queries

---

lib/workload/stateless/stacks/metadata-manager/app/viewsets/lab.py

* This allows dot separator character primary key in API lookup. Such as
'BASE_URL/api/v1/library/lib.01J5TAAXYMXRRMA1VQNGW905AD'

Fixed metadata endpoint allow dot sep in PK

---

lib/workload/stateless/stacks/filemanager/Cargo.lock
lib/workload/stateless/stacks/filemanager/database/migrations/0006_index.sql
lib/workload/stateless/stacks/filemanager/docs/API_GUIDE.md
lib/workload/stateless/stacks/filemanager/filemanager/Cargo.toml
lib/workload/stateless/stacks/filemanager/filemanager/src/queries/list.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/queries/update.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/routes/filter/wildcard.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/routes/get.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/routes/list.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/routes/update.rs

Closes #460
* Rework JSON queries to use jsonpath operators and a gin index.
* The wildcard operators have changed to `*` for multiple characters and `?` for single characters. \cc @williamputraintan 
* Add index for prefix searching on keys.
* Partition records into `current` objects, and `historical` records.

refactor: filemanager indexes

---

lib/workload/stateless/stacks/filemanager/Cargo.lock
lib/workload/stateless/stacks/filemanager/deploy/constructs/functions/api.ts
lib/workload/stateless/stacks/filemanager/deploy/constructs/functions/function.ts
lib/workload/stateless/stacks/filemanager/deploy/constructs/functions/ingest.ts
lib/workload/stateless/stacks/filemanager/deploy/constructs/functions/inventory.ts
lib/workload/stateless/stacks/filemanager/deploy/constructs/functions/migrate.ts
lib/workload/stateless/stacks/filemanager/filemanager-migrate-lambda/Cargo.toml
lib/workload/stateless/stacks/filemanager/filemanager-migrate-lambda/src/main.rs

Related to #460 and #514
The migration Lambda function timed out because the migration involved index creation which can take a while.
* Update migration function timeout to 2 minutes.
* Fix migration Lambda function which was getting stuck in `UPDATE_ROLLBACK_FAILED`.
* The fix involves checking the status of the CloudFormation stack.
* The migration function now uses the built in `CloudFormationCustomResourceRequest` from the `lambda-runtime`.
The migration from #514 doesn't take that long (only about 30 seconds), so for now the simplest solution is to increase the Lambda timeout. Later, it might be an issue if there are any long-running index creation steps.
A better solution could involve:
* Creating an asynchronous migration using the [`isComplete` …

fix: filemanager migration

---

lib/workload/stateless/stacks/workflow-manager/workflow_manager_proc/services/create_workflow_run.py

* WorkflowRun State creation is WRSC timestamp dependant.
It needs to check "time window" condition before saving
and emitting (relaying) WRSC event.

Fixed WorkflowRun State creation business logic

---

lib/workload/stateless/stacks/workflow-manager/workflow_manager_proc/services/create_workflow_run_state.py
lib/workload/stateless/stacks/workflow-manager/workflow_manager_proc/tests/test_create_workflow_run_state.py

- Update Django query to expect and return a single DB record instead of a QuerySet
- Handle DoesNotExist case
- Add new test case to check for this condition

Fix issue with WRSC generation when a libary record exists

---

lib/workload/components/python-metadata-tools-layer/metadata_tools_layer/src/metadata_tools/utils/library_helpers.py
lib/workload/components/python-metadata-tools-layer/metadata_tools_layer/src/metadata_tools/utils/specimen_helpers.py
lib/workload/components/python-metadata-tools-layer/metadata_tools_layer/src/metadata_tools/utils/subject_helpers.py
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/clag/part_1/samplesheet-event-shower/lambdas/generate_event_data_objects_py/generate_event_data_objects.py
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/clag/part_1/samplesheet-event-shower/step_functions_templates/samplesheet_event_shower_sfn_template.asl.json
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/jb-weld/part_2/initialise-cttsov2-library-dbs/step_functions_templates/initialise_cttsov2_library_db_sfn_template.asl.json
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/jb-weld/part_4/fastq-list-row-event-shower-complete-to-cttsov2-draft/step_functions_templates/fastq_list_row_shower_complete_event_to_cttsov2_draft_events_sfn_template.asl.json
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/kwik/part_2/initialise-wgts-library-dbs/step_functions_templates/initialise_wgts_library_db_sfn_template.asl.json
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/kwik/part_4/fastq-list-rows-shower-complete-to-wgts-qc-draft/step_functions_templates/fastq_list_rows_shower_complete_to_wgts_qc_draft_sfn_template.asl.json
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/loctite/part_1/initialise-tn-subject-dbs/step_functions_templates/initialise_tn_subject_db_sfn_template.asl.json
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/loctite/part_2/initialise-tn-library-dbs/step_functions_templates/initialise_tn_library_db_sfn_template.asl.json
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/mod-podge/part_1/initialise-wts-library-dbs/step_functions_templates/initialise_wts_library_db_sfn_template.asl.json
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/pva/part_1/initialise-umccrise-subject-dbs/step_functions_templates/initialise_umccrise_subject_db_sfn_template.asl.json
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/pva/part_2/initialise-umccrise-library-dbs/step_functions_templates/initialise_umccrise_library_db_sfn_template.asl.json

Updated stacky with new metadata manager

---

lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/mod-podge/part_1/initialise-wts-library-dbs/step_functions_templates/initialise_wts_library_db_sfn_template.asl.json
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/pva/part_2/initialise-umccrise-library-dbs/step_functions_templates/initialise_umccrise_library_db_sfn_template.asl.json

Resolves errors for mod-podge and umccrise that failed to initialise fastq list row attributes on samplesheet showers

Payloads use Rgid not RgId

---

lib/workload/components/event-workflowdraftrunstatechange-to-workflowrunstatechange-ready/lambdas/fill_placeholders_in_event_payload_data_py/fill_placeholders_in_event_payload_data.py

Shows production service user can now map to pipeline prod cache bucket

[skip ci]: Add prod example to cache bucket

---

lib/workload/stateless/stacks/bclconvert-manager/deps/requirements.txt
lib/workload/stateless/stacks/bclconvert-manager/translator_service/helper/icav2_analysis/analysis_helper.py
lib/workload/stateless/stacks/bclconvert-manager/translator_service/helper/runinfo/__init__.py
lib/workload/stateless/stacks/bclconvert-manager/translator_service/helper/runinfo/runinfo_helper.py
lib/workload/stateless/stacks/bclconvert-manager/translator_service/helper/samplesheet/samplesheet_helper.py
lib/workload/stateless/stacks/bclconvert-manager/translator_service/icav2_event_translator.py

If there is no lane attribute in the samplesheet bclconvert_data section, collect the runinfo xml and duplicate every row in the samplesheet for every lane in the instrument run

Add lane to bclconvert samplesheet if it doesn't exist

---

lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/workflow_run.py

1. add status query params for filter by the latest status
2. add libraryId and orcabusId in the search terms for group workflow runs
example: 
`http://localhost:8000/api/v1/workflowrun/?search=lib.01J5S9CFX5P69S4KZRQGDFKV1N&status=GENERATING_OUTPUTS`
`http://localhost:8000/api/v1/workflowrun/?search=L2400255&status=READY`

Change(WorkflowRunManager): add more query and search terms

---

lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/jb-weld/part_1/initialise-cttsov2-instrument-dbs/step_functions_templates/initialise_cttsov2_instrument_run_db_sfn_template.asl.json
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/kwik/part_1/initialise-wgts-instrument-run-db/step_functions_templates/initialise_wgts_instrument_run_db_sfn_template.asl.json

sfn event-to-ready will fail when no library has been initialised for this sample type on this run
Resolves #544

Initialise library set to prevent sfn failing

---

lib/workload/stateless/stacks/workflow-manager/workflow_manager/serializers.py
lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/workflow_run.py

Add new api for orcaui `api/v1/workflowrun/count_by_status/` in Workflow Manager
Returns the count of records for each status: 'SUCCEEDED', 'ABORTED', 'FAILED', and 'Onging' State.
UI by status:

add workflow run status count api

---

skel/django-api/README.md
skel/django-api/project_name/tests/test_viewsets.py
skel/django-api/project_name/urls/base.py

* Use `api` as API base instead of service namespace
* Update README with shared DB config setup

Update Python service skel

---

lib/workload/stateless/stacks/filemanager/filemanager-build/src/gen_openapi.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/database/aws/ingester.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/database/aws/ingester_paired.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/events/aws/message.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/queries/list.rs

Closes #563
* Delete markers are ingested as `Deleted` events, rather than `Created` events, which matches what AWS does.
* Fix `filemanager-build` issue which was attempting to parse non Rust files.
* Update delete marker tests.
The justification behind this is that filemanager should try to match what AWS does so that there are no surprises. It is also helpful in ensuring that `current_state` queries don't return `delete_marker` objects which don't represent the current state.

refactor(filemanager): match AWS behaviour for delete markers

---

lib/workload/components/icav2-copy-files/check_or_launch_job_lambda_py/check_or_launch_job_lambda.py
lib/workload/stateless/stacks/cttso-v2-pipeline-manager/lambdas/check_success_py/check_success.py
lib/workload/stateless/stacks/cttso-v2-pipeline-manager/step_functions_templates/set_cttso_v2_nf_outputs.asl.json
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/jb-weld/part_1/initialise-cttsov2-instrument-dbs/step_functions_templates/initialise_cttsov2_instrument_run_db_sfn_template.asl.json
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/kwik/part_1/initialise-wgts-instrument-run-db/step_functions_templates/initialise_wgts_instrument_run_db_sfn_template.asl.json

Handle project copy batch:
* After 'successful' copy, check file sizes are the same between source and destination  #572
Fix cttsov2 outputs json:
* Error when collecting error message, just a typo #571
Roll back library_set init
* Was put in to prevent sfn failure when a sample type was not present on a run but now fails due to dynamodb not supporting empty sets, will find a better solution soon  #570

Bug fixes for 0.2.1

---

lib/workload/components/icav2-copy-files/check_or_launch_job_lambda_py/check_or_launch_job_lambda.py
lib/workload/components/icav2-copy-files/index.ts

Quick fix for bssh fastq copy error (will also need to apply patch to the cttsov2 pipeline manager since this also uses the same copy technique)

Fix error when checking source uris have been transferred

---

lib/workload/stateless/stacks/filemanager/database/migrations/0002_s3_ingest_id.sql
lib/workload/stateless/stacks/filemanager/database/migrations/0002_s3_move_id.sql
lib/workload/stateless/stacks/filemanager/database/queries/api/select_existing_by_bucket_key.sql
lib/workload/stateless/stacks/filemanager/database/queries/ingester/aws/insert_s3_created_objects.sql
lib/workload/stateless/stacks/filemanager/database/queries/ingester/aws/insert_s3_objects.sql
lib/workload/stateless/stacks/filemanager/database/queries/ingester/aws/update_reordered_for_created.sql
lib/workload/stateless/stacks/filemanager/database/queries/ingester/aws/update_reordered_for_deleted.sql
lib/workload/stateless/stacks/filemanager/deploy/constructs/functions/api.ts
lib/workload/stateless/stacks/filemanager/deploy/constructs/functions/function.ts
lib/workload/stateless/stacks/filemanager/deploy/constructs/functions/ingest.ts
lib/workload/stateless/stacks/filemanager/docs/MOVED_OBJECTS.md
lib/workload/stateless/stacks/filemanager/filemanager/src/clients/aws/s3.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/database/aws/ingester.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/database/aws/ingester_paired.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/database/entities/s3_object.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/database/mod.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/env.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/error.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/events/aws/collecter.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/events/aws/inventory.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/events/aws/message.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/events/aws/mod.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/events/mod.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/handlers/aws.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/queries/list.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/queries/mod.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/routes/filter/mod.rs

Closes #584
* Introduces a mechanism by which the filemanager can track how an object moves by using S3 tags.
* For each object, a tag is added to S3 to track the `ingest_id`.
* The ingest id gets copied to the database as well.
* When an object is moved with tags, the `ingest_id` is reused, which allows creating the sequence of records representing the moved object.
* Attributes are also copied as the object moves.
* Added `GetObjectTagging` and `PutObjectTagging` capabilities to filemanager.
* Added `ingest_id` column to database which matches the `ingest_id` on the S3 object tags.
* Test cases for move logic.

feat(filemanager): ingest_id tagging and object move tracking

---

lib/workload/stateless/stacks/filemanager/deploy/constructs/functions/api.ts
lib/workload/stateless/stacks/filemanager/deploy/constructs/functions/function.ts
lib/workload/stateless/stacks/filemanager/deploy/constructs/functions/ingest.ts
lib/workload/stateless/stacks/filemanager/deploy/constructs/functions/inventory.ts
lib/workload/stateless/stacks/filemanager/filemanager/src/clients/aws/s3.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/events/aws/collecter.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/events/aws/inventory.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/routes/presign.rs

Closes #586
Depends on #585
* Use version_ids for `HeadObject`, `GetObjectTagging`, `PutObjectTagging` and presigned `GetObject` requests.
* If versioning is not enabled, then the default `"null"` string version is used, which lines up with how AWS treats buckets without versioning enabled.

fix(filemanager): version_id for S3 API calls

---

lib/workload/stateless/stacks/filemanager/docs/API_GUIDE.md
lib/workload/stateless/stacks/filemanager/filemanager/src/events/aws/collecter.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/queries/list.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/queries/update.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/routes/filter/mod.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/routes/get.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/routes/list.rs

Closes #595 
* The filemanager API can now accept multiple keys in the API, where each additional key represents an `or` statement in the SQL query.
* Additional keys need to use the `[]` syntax to specify a list. E.g. `/api/v1/s3?key[]=key1&key[]=key2`.
* Multiple keys are also supported on attributes.
* The logic involving attributes has been fixed so that JSON arrays represent an `or` condition.

feat(filemanager): accept multiple keys in API

---

lib/workload/stateless/stacks/metadata-manager/README.md
lib/workload/stateless/stacks/metadata-manager/app/management/commands/load_from_csv.py
lib/workload/stateless/stacks/metadata-manager/app/management/commands/trigger_sync_handler.py
lib/workload/stateless/stacks/metadata-manager/deploy/README.md
lib/workload/stateless/stacks/metadata-manager/handler/load_custom_metadata_csv.py
lib/workload/stateless/stacks/metadata-manager/handler/sync_tracking_sheet.py
lib/workload/stateless/stacks/metadata-manager/proc/service/load_csv_srv.py
lib/workload/stateless/stacks/metadata-manager/proc/service/tracking_sheet_srv.py
lib/workload/stateless/stacks/metadata-manager/proc/tests/test_tracking_sheet_srv.py

Fixes where it loads records where their internal Ids (e.g. `individualId`) are still null (as it is incomplete entry) by dropping the record entirely.

Fix: Drop incomplete record before metadata processing

---

lib/workload/stateless/stacks/cttso-v2-pipeline-manager/deploy/constructs/cttsov2-icav2-manager/index.ts

Error created when cdk-nag forced us to use our own policy statement instead of 'grantRead', missed this permission

cttsov2 job checker requires permissions to list executions

---

lib/workload/stateless/stacks/workflow-manager/workflow_manager/models/base.py
lib/workload/stateless/stacks/workflow-manager/workflow_manager/tests/test_models.py

Fixes https://github.com/umccr/orcabus/issues/611

Handle orcabus_id with prefix when saving model objects

---

lib/workload/stateless/stacks/filemanager/Makefile
lib/workload/stateless/stacks/filemanager/database/migrations/0003_partition_state.sql
lib/workload/stateless/stacks/filemanager/database/migrations/0003_s3_current_state.sql
lib/workload/stateless/stacks/filemanager/database/queries/api/reset_current_state.sql
lib/workload/stateless/stacks/filemanager/database/queries/api/select_existing_by_bucket_key.sql
lib/workload/stateless/stacks/filemanager/database/queries/ingester/aws/insert_s3_objects.sql
lib/workload/stateless/stacks/filemanager/database/queries/ingester/aws/update_reordered_for_created.sql
lib/workload/stateless/stacks/filemanager/database/queries/ingester/aws/update_reordered_for_deleted.sql
lib/workload/stateless/stacks/filemanager/deploy/constructs/functions/migrate.ts
lib/workload/stateless/stacks/filemanager/docs/ARCHITECTURE.md
lib/workload/stateless/stacks/filemanager/filemanager-api-server/src/main.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/database/aws/ingester.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/database/aws/ingester_paired.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/database/aws/query.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/database/entities/s3_object.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/database/mod.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/events/aws/collecter.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/events/aws/inventory.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/events/aws/message.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/events/aws/mod.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/handlers/aws.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/queries/get.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/queries/list.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/queries/mod.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/queries/update.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/routes/get.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/routes/list.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/routes/pagination.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/routes/update.rs

Related to #614, finishes first task.
* Add `is_current_state` column to database for later partitioning.
* Migrates existing data to the correct `is_current_state`.
* API uses this column now instead of performing the calculation every time.
* Tests are updated to take this into account.
I know this adds some overhead to the ingester, but it is performing pretty well in testing (< a few ms per insert), and I think it's worth it because it reduces the performance issues on the API side. If this ever is a problem for the ingester to handle, then it can always be run as a separate asynchronous process.

feat: filemanager partitions

---

lib/workload/stateless/stacks/filemanager/database/migrations/0003_s3_current_state.sql
lib/workload/stateless/stacks/filemanager/database/queries/api/reset_current_state.sql
lib/workload/stateless/stacks/filemanager/docs/ARCHITECTURE.md
lib/workload/stateless/stacks/filemanager/filemanager/src/database/aws/ingester.rs

Related to #614 and #615.
* Fixes the reset current state logic to include old versions of objects.
* Now, when the query is executed, it flips `is_current_state` to false for old versions of objects too. Previously this was keeping every versioned object as "current".
I realised that versioned objects need to be reset in the `is_current_state` query too, because old versions of objects do not represent current state (thanks @reisingerf with [this](https://github.com/umccr/orcabus/pull/615#discussion_r1815920837) comment).
Performance is similar for this query as it was when `version_id` was included in the `where` clause. Note that I don't think there will be many more objects included in the set. Only one copy of a bucket/key combination should be included because the query only needs …

fix(filemanager): resetting current state should include old verisons

---

config/constants.ts
config/stacks/stackyMcStackFace.ts
lib/workload/stateful/stacks/stacky-mcstackface-dynamodb/index.ts
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/index.ts

InputMakerTable and WorkflowTable had uses prior to generation of the workflowmanager which now stores runs.  
Tables no longer needed

Remove unused stacky tables

---

config/stacks/shared.ts
lib/workload/stateful/stacks/shared/constructs/event-source/index.ts
test/stateful/shared/eventSourceConstruct.test.ts

Related to https://github.com/umccr/infrastructure/pull/489
* Ignore cache directories under `byob-icav2` when processing incoming EventBridge events, and only forward `Created` and `Deleted` events to filemanager.

feat(event-source): ignore cache directories

---

config/constants.ts
config/stacks/shared.ts

Related to https://github.com/umccr/infrastructure/pull/490
* Adds archive bucket as event source for filemanager.

feat(event-source): add archive bucket as event source

---

lib/workload/stateless/stacks/workflow-manager/workflow_manager_proc/services/create_workflow_run_state.py
lib/workload/stateless/stacks/workflow-manager/workflow_manager_proc/tests/test_create_workflow_run_state.py

As noted in the test:
- for library lookup and library record generation a "sanitised" `orcabusId` is used (e.g. ULID only, prefix stripped off)
- for the event relay the original values from the input event are forwarded as is to the output event
(not a permanent nor elegant solution)

Fix library lookup with prefixed orcabusId

---

lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/nails/part_2/cttso-v2-output-to-pieriandx-ready-event/index.ts
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/nails/part_2/cttso-v2-output-to-pieriandx-ready-event/lambdas/get_data_from_redcap_py/get_data_from_redcap.py
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/nails/part_2/cttso-v2-output-to-pieriandx-ready-event/lambdas/get_deidentified_case_metadata_py/get_deidentified_case_metadata.py

Note that this still doesn't seem to fix the issue.
https://ap-southeast-2.console.aws.amazon.com/states/home?region=ap-southeast-2#/v2/executions/details/arn:aws:states:ap-southeast-2:843407916570:execution:nails-cttsov2-complete-to-pdx-sfn:f9fde40f-5986-437a-80b5-adcc0f34f07e
Fails because the 'get recap info' step times out.  
Most recent logs don't show anything
https://ap-southeast-2.console.aws.amazon.com/cloudwatch/home?region=ap-southeast-2#logsV2:log-groups/log-group/$252Faws$252Flambda$252FOrcaBusBeta-StackyMcStack-cttsov2topieriandxgetDat-K0RFO3ts0afo/log-events/2024$252F10$252F31$252F$255B7$255Dd4b12f54af964991a4c0244662496c1f
Max memory used is only about 116 Mb, far shy of the 2048 limit.

Upgrade memory for pieriandx glue lambdas

---

lib/workload/stateless/stacks/bclconvert-manager/translator_service/helper/runinfo/runinfo_helper.py
lib/workload/stateless/stacks/bclconvert-manager/translator_service/helper/samplesheet/samplesheet_helper.py

Tested with 
```
num_lanes = get_num_lanes_from_run_info(
project_id="9ec02c1f-53ba-47a5-854d-e6b53101adb7",
data_id="fil.7d86703bc9e2424c441d08dcf9e059fc"  #/ilmn-runs/bssh_aps2-sh-prod_4515537/RunInfo.xml
)
)
print(num_lanes)
v2_samplesheet_dict = v2_samplesheet_reader(
StringIO(
read_icav2_file_contents_to_string(
project_id="9ec02c1f-53ba-47a5-854d-e6b53101adb7",
data_id="fil.b4534c47c0d5481075d308dcfabfb3a9"  #/ilmn-runs/bssh_aps2-sh-prod_4515537/SampleSheet.csv
)
)
)
v2_samplesheet_dict['bclconvert_data'] = list(flatten(
map(
lambda bclconvert_data_row_iter: list(
map(
lambda lane_iter: {
**bclconvert_data_row_iter,
**{"lane": lane_iter + 1}
},
range(num_lanes)
)
),
v2_samplesheet_dict['bclconvert_data']
),
))
print(
json.dumps(
v2_samplesheet_dict,
indent=4
)
)
```
Returns
```
4
{ …
```

Need to set 'keep_flowcell_layout' to true for wrapica collection of runinfo xml

---

lib/workload/stateless/stacks/metadata-manager/app/viewsets/sync.py

Will allow description to be `None`
Related #627

Fix (MM): Allow nullable description for sync

---

lib/workload/stateless/stacks/cttso-v2-pipeline-manager/deploy/constructs/cttsov2-icav2-manager/index.ts

Set cttsov2 icav2 storage configuration to LARGE

---

lib/workload/stateless/stacks/pieriandx-pipeline-manager/lambdas/generate_pieriandx_objects_py/generate_pieriandx_objects.py
lib/workload/stateless/stacks/pieriandx-pipeline-manager/layers/src/pieriandx_pipeline_tools/pieriandx_lookup/get_disease_label.py
lib/workload/stateless/stacks/pieriandx-pipeline-manager/layers/src/pieriandx_pipeline_tools/pieriandx_lookup/get_specimen_label.py

Workaround until codepipeline supports Git LFS
Workaround for #653

Pull the snomed databases from github if they're not on the local system

---

lib/workload/stateless/stacks/ora-compression-manager/deploy/index.ts
lib/workload/stateless/stacks/ora-compression-manager/lambdas/merge_file_sizes_for_fastq_list_rows_py/merge_file_sizes_for_fastq_list_rows.py
lib/workload/stateless/stacks/ora-compression-manager/step_functions_templates/fastq_list_row_compression_event.asl.json
lib/workload/stateless/stacks/ora-compression-manager/step_functions_templates/set_compression_outputs.asl.json

Resolves #655
At a later stage, worth retrieving the samplesheets from the input instrument run to get the actual fastq list row ids

fix-ora-compression-manager

---

config/constants.ts
lib/workload/stateless/stacks/pieriandx-pipeline-manager/deploy/index.ts
lib/workload/stateless/stacks/pieriandx-pipeline-manager/lambdas/generate_output_data_payload_py/generate_output_data_payload.py
lib/workload/stateless/stacks/pieriandx-pipeline-manager/lambdas/get_informaticsjob_and_report_status_py/get_informaticsjob_and_report_status.py
lib/workload/stateless/stacks/pieriandx-pipeline-manager/lambdas/upload_pieriandx_sample_data_to_s3_py/upload_pieriandx_sample_data_to_s3.py
lib/workload/stateless/stacks/pieriandx-pipeline-manager/layers/src/pieriandx_pipeline_tools/utils/s3_helpers.py
lib/workload/stateless/stacks/pieriandx-pipeline-manager/step_function_templates/launch_pieriandx.asl.json
lib/workload/stateless/stacks/pieriandx-pipeline-manager/step_function_templates/monitor_runs.asl.json
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/nails/part_2/cttso-v2-output-to-pieriandx-ready-event/lambdas/get_data_from_redcap_py/get_data_from_redcap.py

* Prod PierianDx bucket requires KMS encryption
* Can't use LATEST version for invocation of 'collectPierianDxAccessToken'
* Use '*' on function name followed by NagSuppression
* Fix SSM parameter determining the path of the PierianDx bucket
* Differences between requesting_physicians_x_name and requetsing_physician_x_name was causing default name to be used (Sean)
* Wrong JSON path used in SFN to collect the panel version
* Report ID stored in database as an integer not as a string
* Fixed GET for linked libraries which had an incorrect JSON path when pushing a workflow run state change event
* Fixed analysis path generation for data outputs
P.S have already pushed this to OrcaBus Prod manually

PierianDx Production Fixes

---

config/constants.ts
lib/workload/stateless/stacks/tumor-normal-pipeline-manager/lambdas/get_boolean_parameters_from_event_input_py/get_boolean_parameters_from_event_input.py

Dragen somatic with germline pipeline didn't have the enable_cnv_somatic flag available in the workflow (and in the past we have just used enable_cnv), since we do not need the cnv on the germline calls we use just enable_cnv_somatic instead.
Updated ssm parameter in dev/stg and prod

Update dragen somatic pipeline id

---

config/stacks/fileManager.ts
lib/workload/stateless/stacks/filemanager/deploy/stack.ts

Closes #669 
* Gives the API and inventory functions access the `orcabus_file_manager_ingest_access` role. This allows the API function to create valid presigned URLs, and the inventory function to correctly get object metadata before ingesting.

hotfix(filemanager): add permissions that allow API/inventory functions to access `pipeline-*-cache` buckets

---

lib/workload/stateless/stacks/ora-compression-manager/deploy/index.ts
lib/workload/stateless/stacks/ora-compression-manager/lambdas/set_outputs_json_py/set_outputs_json.py
lib/workload/stateless/stacks/ora-compression-manager/step_functions_templates/fastq_list_row_compression_event.asl.json
lib/workload/stateless/stacks/ora-compression-manager/step_functions_templates/set_compression_inputs.asl.json
lib/workload/stateless/stacks/ora-compression-manager/step_functions_templates/set_compression_outputs.asl.json

Resolves #660 
Will make it easier to track which runs have been compressed

Setup to rearrange the outputs for the ora compression manager

---

config/constants.ts
config/stacks/shared.ts

Similar to https://github.com/umccr/orcabus/pull/625
* Adds fastq bucket as event source for filemanager.
I think this will need a change to the role similar to [this](https://github.com/umccr/infrastructure/blob/586a87926c90f9c913170096f5670105586abd4f/terraform/stacks/unimelb/data_archive/analysis_archive.tf#L76-L101)?

feat(filemanager): add fastq bucket to ingester event source

---

lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/workflow_run.py

Duplicate workflows when using workflow search: https://github.com/umccr/orca-ui/issues/82
The duplicate results occur because of the OR conditions in the search query combined with the related table joins. And The duplicate results occur selectively because of how JOIN operations work with OR conditions in the search query. 
No Duplicates Case:
```sql
-- When searching only direct fields (workflow_run_name or comment)
-- Example search: "test" matching workflow_run_name
SELECT * FROM workflow_run 
WHERE workflow_run_name ILIKE '%test%'
-- No JOINs needed = No duplicates
```
Duplicates Case:
```sql
-- When searching related fields (libraries or workflow)
-- Example search: "oncoanalyser_wgs" matching multiple libraries
SELECT workflow_run.* 
FROM workflow_run 
JOIN libraries ON …
```

add distinct to remove duplicate results

---

config/constants.ts
lib/workload/components/python-lambda-get-workflow-payload/get_workflow_payload_py/get_workflow_payload.py
lib/workload/components/python-lambda-get-workflow-payload/index.ts
lib/workload/components/python-lambda-list-service-instances/index.ts
lib/workload/components/python-lambda-list-service-instances/list_service_instances_py/list_service_instances.py
lib/workload/components/python-lambda-service-discovery/index.ts
lib/workload/components/python-lambda-service-discovery/service_discovery_py/service_discovery.py
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/jb-weld/index.ts
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/jb-weld/part_4/launch-holmes-extract-event/index.ts
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/jb-weld/part_4/launch-holmes-extract-event/step_functions_templates/cttsov2_complete_to_holmes_bam_extraction_sfn_template.asl.json
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/kwik/index.ts
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/kwik/part_6/launch-holmes-extract-event/index.ts
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/kwik/part_6/launch-holmes-extract-event/step_functions_templates/holmes_extract_wrapper_sfn_template.asl.json

After LibraryQC is complete, trigger the holmes stack to extract all bams from all library lanes.  
After cttsov2 is complete, extract the bam file from the logs intermediates folder.

Add holmes glue

---

lib/workload/components/gzip-raw-md5sum-fq-pair-sfn/step_functions_templates/get_raw_md5sum_for_fastq_gzip_pair_template.asl.json
lib/workload/components/ora-file-decompression-fq-pair-sfn/step_functions_templates/decompress_ora_fastq_pair_sfn_template.asl.json

Backoff of 5 means a second retry will retry in five minutes, and then 25 minutes, then in 125 minutes
https://repost.aws/knowledge-center/ecs-fargate-runtask-capacity

Retry 5 mins when capacity is limited

---

cdk.json
lib/pipeline/statefulPipelineStack.ts
lib/pipeline/statelessPipelineStack.ts

Reshuffle the order of deployment: Automatic deployment to staging > manual to prod > manual to dev. Dev is still in the pipeline so that we can deploy changes with a button rather than `cdk deploy` locally.

Feat(pipeline): Disable Dev Automatic Deployment

---

config/constants.ts
lib/workload/components/gzip-raw-md5sum-fq-pair-sfn/index.ts
lib/workload/components/gzip-raw-md5sum-fq-pair-sfn/step_functions_templates/ecs_task_rate_limiters_sfn_template.asl.json
lib/workload/components/gzip-raw-md5sum-fq-pair-sfn/step_functions_templates/get_raw_md5sum_for_fastq_gzip_pair_template.asl.json
lib/workload/components/ora-file-decompression-fq-pair-sfn/index.ts
lib/workload/components/ora-file-decompression-fq-pair-sfn/step_functions_templates/decompress_ora_fastq_pair_sfn_template.asl.json
lib/workload/components/ora-file-decompression-fq-pair-sfn/step_functions_templates/ecs_task_rate_limiters_sfn_template.asl.json
lib/workload/stateless/stacks/ora-compression-manager/deploy/index.ts
lib/workload/stateless/stacks/ora-compression-manager/step_functions_templates/get_raw_md5sum_for_all_fastq_gzips_sfn_template.asl.json
lib/workload/stateless/stacks/ora-compression-manager/step_functions_templates/get_raw_md5sum_for_all_fastq_ora_sfn_template.asl.json
lib/workload/stateless/stacks/ora-compression-manager/step_functions_templates/rate_limit_get_raw_md5sum_for_fastq_gzip_sfn_template.asl.json
lib/workload/stateless/stacks/ora-compression-manager/step_functions_templates/rate_limit_get_raw_md5sum_for_fastq_ora_sfn_template.asl.json
lib/workload/stateless/stacks/ora-compression-manager/step_functions_templates/set_compression_inputs.asl.json
lib/workload/stateless/stacks/ora-compression-manager/step_functions_templates/set_compression_outputs.asl.json

1. Rate limit the number of concurrent ecs tasks to 400
2. Rate limit the number of concurrent instrument runs either gzip -> md5sum or ora -> md5sum to 10
Resolves #718

Rate limit ora compression workflow

---

lib/workload/stateless/stacks/pieriandx-pipeline-manager/lambdas/generate_pieriandx_objects_py/generate_pieriandx_objects.py

The portal run id is already part of the case accession id, which is why it is currently duplicated
Resolves #729

Don't extend portal run id to sequencer run,

---

lib/workload/components/gzip-raw-md5sum-fq-pair-sfn/step_functions_templates/ecs_task_rate_limiters_sfn_template.asl.json
lib/workload/components/ora-file-decompression-fq-pair-sfn/step_functions_templates/ecs_task_rate_limiters_sfn_template.asl.json
lib/workload/stateless/stacks/ora-compression-manager/step_functions_templates/set_compression_outputs.asl.json

Quick fix, reduce max number of simultaneous ECS tasks to 99

Max results can't be more than 100

---

lib/workload/stateless/stacks/data-migrate/data_mover/cli.py
lib/workload/stateless/stacks/data-migrate/data_mover/data_mover.py
lib/workload/stateless/stacks/data-migrate/poetry.lock
lib/workload/stateless/stacks/data-migrate/pyproject.toml

Related to https://github.com/umccr/orcabus/pull/726
* Fixes stdout capture so that the task fails if the last sync contains output.
* Signals to the step function to fail the step on exceptions to avoid the step function hanging until timeout.

fix(data-migrate): fix stdout capture and failed step functions

---

lib/workload/stateless/stacks/data-migrate/data_mover/cli.py
lib/workload/stateless/stacks/data-migrate/data_mover/data_mover.py
lib/workload/stateless/stacks/data-migrate/poetry.lock

Related to https://github.com/umccr/orcabus/issues/721
* Instead of trying to output the full `stdout` of `aws s3 sync` from the step functions ECS task, use a simplified structured output to avoid the payload limit error.
* Fix output logs so that they show in CloudWatch.

fix(data-migrate): add structured output to step functions

---

lib/workload/stateless/stacks/workflow-manager/workflow_manager/urls/base.py
lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/workflow_run_stats.py

add statistics api for workflow run manger for all statistics and analysis of runs data
two stats api will be add:
`/api/v1/workflowrun/stats/list_all/`
`/api/v1/workflowrun/stats/count_by_status/`
couple with report page (in development) in UI: https://github.com/umccr/orca-ui/pull/65

Feat (wfm): add workflow stats viewsets

---

config/constants.ts
config/stacks/tumorNormalPipelineManager.ts
lib/workload/stateless/stacks/tumor-normal-pipeline-manager/deploy/index.ts
lib/workload/stateless/stacks/tumor-normal-pipeline-manager/lambdas/add_ora_reference_py/add_ora_reference.py
lib/workload/stateless/stacks/tumor-normal-pipeline-manager/step_functions_templates/set_tn_cwl_inputs_sfn.asl.json

Resolves #697
Updated workflow that supports ora reference as input

Add ora reference for tn workflows

---

lib/workload/components/ora-file-decompression-fq-pair-sfn/tasks/ora_decompression/docker-entrypoint.sh
lib/workload/stateless/stacks/cttso-v2-pipeline-manager/deploy/constructs/cttsov2-icav2-manager/index.ts
lib/workload/stateless/stacks/cttso-v2-pipeline-manager/deploy/stack.ts
lib/workload/stateless/stacks/cttso-v2-pipeline-manager/lambdas/check_fastq_list_row_is_ora_py/check_fastq_list_row_is_ora.py
lib/workload/stateless/stacks/cttso-v2-pipeline-manager/lambdas/convert_ora_to_cache_uri_gz_path_py/convert_ora_to_cache_uri_gz_path.py
lib/workload/stateless/stacks/cttso-v2-pipeline-manager/step_functions_templates/set_cttso_v2_nf_inputs.asl.json

Add ora reference for cttso workflows

Add ora compression to cttsov2 workflow

---

config/config.ts
config/stacks/htsget.ts
lib/workload/stateless/stacks/filemanager/deploy/stack.ts
lib/workload/stateless/stacks/filemanager/docs/API_GUIDE.md
lib/workload/stateless/stacks/htsget/README.md
lib/workload/stateless/stacks/htsget/deploy.toml
lib/workload/stateless/stacks/htsget/stack.ts
lib/workload/stateless/statelessStackCollectionClass.ts
package.json
yarn.lock

Closes #758 
* Enables htsget-rs support for all htsget-compatible filemanager files.
* This reuses the filemanager-ingest-role to access files.
* The htsget-rs endpoint can be queried using `https://htsget-file.<stage>.umccr.org`.
See related PR https://github.com/umccr/htsget-deploy/pull/1

feat(htsget): add htsget support

---

config/stacks/shared.ts
lib/workload/stateful/stacks/shared/constructs/database/index.ts
test/stateful/pipeline/deployment.test.ts

* This extends point-in-time (PIT) recovery objective (RPO) upto 7 days
in production RDS aurora cluster. Staging and development maintain
1 day RPO.

Updated aurora automated backup retention

---

lib/workload/components/api-gateway/index.ts
lib/workload/stateless/stacks/metadata-manager/app/tests/test_viewsets.py
lib/workload/stateless/stacks/metadata-manager/app/tests/utils.py
lib/workload/stateless/stacks/metadata-manager/app/viewsets/base.py
lib/workload/stateless/stacks/metadata-manager/app/viewsets/contact.py
lib/workload/stateless/stacks/metadata-manager/app/viewsets/individual.py
lib/workload/stateless/stacks/metadata-manager/app/viewsets/library.py
lib/workload/stateless/stacks/metadata-manager/app/viewsets/project.py
lib/workload/stateless/stacks/metadata-manager/app/viewsets/sample.py
lib/workload/stateless/stacks/metadata-manager/app/viewsets/subject.py
lib/workload/stateless/stacks/metadata-manager/deploy/construct/lambda-api/index.ts

- Add Deletion and Patch endpoint for each metadata model (JWT email token will track the user)
- Add `is_library_none` filter to Sample and Subject model to find the library-less entity
Resolve #575

Feat(MM): Additional MM Endpoint and Library Filter

---

config/stacks/shared.ts
lib/workload/stateful/stacks/shared/constructs/database/index.ts
test/stateful/pipeline/deployment.test.ts
test/stateful/shared/databaseConstruct.test.ts

* Leveraged AWS Backup service to set up long term tier-2 backup
retention in production. Assert with test harness to make sure
compliance rule is enforced in production configuration.
Resolves #178

Implemented OrcaBus database tier-2 backup retention

---

lib/workload/stateless/stacks/workflow-manager/workflow_manager/serializers/workflow_run.py
lib/workload/stateless/stacks/workflow-manager/workflow_manager/serializers/workflow_run_action.py
lib/workload/stateless/stacks/workflow-manager/workflow_manager/urls/base.py
lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/state.py
lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/workflow_run_action.py
lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/workflow_run_stats.py

Resolve: https://github.com/umccr/orcabus/issues/695
1. add "DEPRECATED" state change for "SUCCEEDED" 
2. add validate process for new state change 
new api for  and rerun
`/api/v1/workflowrun/{orcabusId}/state/valid_states_map/`
`/api/v1/workflowrun/{orcabusId}/validate_rerun_workflows/`
couple with UI PR https://github.com/umccr/orca-ui/pull/92

Feat(wfr) api add "DEPRECATED" state

---

lib/workload/stateless/stacks/pg-dd/.env.example
lib/workload/stateless/stacks/pg-dd/Dockerfile
lib/workload/stateless/stacks/pg-dd/deploy/stack.ts
lib/workload/stateless/stacks/pg-dd/pg_dd/handler.py
lib/workload/stateless/stacks/pg-dd/pg_dd/pg_dd.py
lib/workload/stateless/stacks/pg-dd/poetry.lock
lib/workload/stateless/stacks/pg-dd/pyproject.toml

Closes #782
* Downgrade python version to 3.12.
* Update environment variables in Lambda function.

fix(pg-dd): python version and environment variables

---

lib/workload/stateless/stacks/transcriptome-pipeline-manager/step_functions_templates/set_wts_cwl_inputs_sfn.asl.json

This occurs when no fastqs are in ora format and therefore the ora reference is omitted. 
Created this step with JSONata.
@andrewpatto kinda annoying this JSONata wasn't introduced earlier (like six months ago, before I built around 70 different step functions). It's so much easier to handle / transform data in JSONata compared to JSONPath, AND there are online emulators available to help validate things prior to writing. 
A step function can now be JSONPath or JSONata, to help onboarding, the allow one to place a JSONata task INSIDE a JSONPath step function (and vice versa)
One downside is this compatibility between JSONPath and JSONata within AWS Step Functions is a bit flaky. 
For example the JSONata 'variables' functionality isn't parsed into downstream steps if the overall workflow …

Remove null inputs from inputs payload

---

config/stacks/fileManager.ts
test/stateless/deployment.test.ts

Closes #790 
* Fixes missing permissions that let the filemanager tag objects in the archive analysis and fastq buckets.

fix(filemanager): add permissions for analysis and fastq archive buckets

---

lib/workload/stateless/stacks/filemanager/docs/API_GUIDE.md
lib/workload/stateless/stacks/filemanager/filemanager/src/queries/update.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/routes/update.rs

Closes #792
* Adds method to update the `ingestId` using the existing JSON patch routes. This is only allowed to update if the `ingestId` column is null, it cannot overwrite an existing `ingestId`.

feat(filemanager): update ingest id

---

lib/workload/stateless/stacks/metadata-manager/app/settings/base.py
lib/workload/stateless/stacks/metadata-manager/app/settings/local.py
lib/workload/stateless/stacks/metadata-manager/app/urls/base.py
lib/workload/stateless/stacks/metadata-manager/app/urls/local.py
lib/workload/stateless/stacks/metadata-manager/deploy/construct/lambda-api/index.ts
lib/workload/stateless/stacks/sequence-run-manager/deploy/stack.ts
lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/settings/base.py
lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/settings/local.py
lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/urls/base.py
lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/urls/local.py
lib/workload/stateless/stacks/workflow-manager/deploy/stack.ts
lib/workload/stateless/stacks/workflow-manager/workflow_manager/settings/base.py
lib/workload/stateless/stacks/workflow-manager/workflow_manager/settings/local.py
lib/workload/stateless/stacks/workflow-manager/workflow_manager/urls/base.py
lib/workload/stateless/stacks/workflow-manager/workflow_manager/urls/local.py
skel/django-api/deploy/stack.ts
skel/django-api/project_name/settings/base.py
skel/django-api/project_name/settings/local.py

Only in Django Microservice
- Move swagger local to the deployable endpoint
- Change swagger path (from `/swagger-ui`) to `/schema/swagger-ui`
- Add NoneAuth for all path prefix with `/schema` endpoint in API-GW
cc: @raylrui @mmalenic

Feat: Django Deployable Swagger

---

lib/workload/stateless/stacks/cttso-v2-pipeline-manager/step_functions_templates/set_cttso_v2_nf_inputs.asl.json

Remove copy job id from step functions result path
Resolves #795

Fix cttso input maker sfn

---

lib/workload/stateless/stacks/workflow-manager/workflow_manager/serializers/base.py

The removal in #784 is not intended. The re-run workflow depends on this to dispatch the correct JSON format to the EB.
Fix [slack-thread](https://umccr.slack.com/archives/C03ABJTSN7J/p1736120499759199?thread_ts=1734914138.553039&cid=C03ABJTSN7J)

fix(WFM): Put Back `camelCase` Serializer

---

lib/workload/stateless/stacks/htsget/stack.ts
package.json
yarn.lock

* Add the `gitReference` when fetching htsget-rs to avoid errors with versions from the main branch.
This should fix build errors in #800 /cc @williamputraintan

fix(filemanager): pin htsget-rs version inside the htsget stack

---

lib/workload/stateless/stacks/filemanager/deploy/stack.ts
lib/workload/stateless/stacks/filemanager/filemanager-api-server/src/main.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/routes/error.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/routes/openapi.rs

Closes #802 
Related #797
* Move swagger to `/schema/swagger-ui` and make it no-auth on the API gateway so it can be accessed when deployed.

feat(filemanager): deployable swagger ui

---

package.json
yarn.lock

Related #758 
Related PR: https://github.com/umccr/htsget-deploy/pull/6
* Update `htsget-lambda` with `aws-cdk-lib` peer dependency so that the `aws-cdk-lib` dependency can be updated in orcabus.

build: update htsget-lambda dependency

---

config/stacks/sampleSheetChecker.ts
lib/workload/stateless/stacks/sample-sheet-check/sample-sheet-check-lambda/src/metadata.py
lib/workload/stateless/stacks/sample-sheet-check/stack.ts

`umccr_domain` parameter name does not exist in every stage account. Will put the metadata domain name as a config stack.

fix(sscheck): change metadata reference domain name

---

lib/workload/stateful/stacks/token-service/token_service/cognitor/__init__.py
lib/workload/stateful/stacks/token-service/token_service/cognitor/tests.py
lib/workload/stateful/stacks/token-service/token_service/rotate_service_jwt.py
lib/workload/stateful/stacks/token-service/token_service/rotate_service_user.py

Closes #811 
* Ensure that the required characters are always present in generated password to prevent the secret rotation from failing.
* Cognito allows defining password requirements, in this case the password should have at least 1 uppercase, lowercase, numeric, and special characters: https://docs.aws.amazon.com/cognito/latest/developerguide/managing-users-passwords.html

fix(token-service): generated password should contain required characters

---

lib/workload/stateless/stacks/sample-sheet-check/sample-sheet-check-lambda/handler.py
lib/workload/stateless/stacks/sample-sheet-check/sample-sheet-check-lambda/src/checker.py
lib/workload/stateless/stacks/sample-sheet-check/sample-sheet-check-lambda/src/logger.py
lib/workload/stateless/stacks/sample-sheet-check/stack.ts

- Enable back AWS lambda logging to CloudWatch
- On failed validation, return the error name to clarify the problem from the sample sheet

Chore(sscheck): Re-enable logging and detailed error message

---

lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/viewsets/comment.py
lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/viewsets/state.py
lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/state.py
lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/workflow_run_comment.py
lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/workflow_run_stats.py

1. lookup_value_regex = "[^/]+" # to allow id prefix like 'seq.' in the url
2. remove prefix when prefix added in "associated_id"

add lookup_value_regex to allow special char in url

---

lib/pipeline/statelessPipelineStack.ts

Closes #812 
* Enables logging on the github action runner to address security hub control: https://docs.aws.amazon.com/securityhub/latest/userguide/codebuild-controls.html#codebuild-4

fix(pipeline): enable logging on github action runner

---

lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager_proc/domain/sequence.py
lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager_proc/lambdas/bssh_event.py
lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager_proc/services/sequence_srv.py
lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager_proc/services/sequence_state_srv.py

Sequence Run Manager service refactor
1. add detail state record for srm_srv states
2. add comment for "Sequence completed", "Sequence completed. But failed in post analysis process.", and "Sequence failed."
fix #848

refactor srm srv for detail states and comment

---

lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/state.py

Make deprecated state available for ready runs
fix #846

deprecated available for ready runs

---

lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/clag/part_2/fastq-list-rows-event-shower/index.ts
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/clag/part_2/fastq-list-rows-event-shower/lambdas/generate_event_data_objects_py/generate_event_data_objects.py
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/clag/part_2/fastq-list-rows-event-shower/step_functions_templates/fastq_list_row_event_shower_sfn_template.asl.json

Write event objects to database and then iterate over the ids to then extract events from db and publish to event bus, rather than carry the information through the step functions

Update clag to handle large amounts of fastq files

---

lib/workload/stateless/stacks/workflow-manager/workflow_manager/errors.py
lib/workload/stateless/stacks/workflow-manager/workflow_manager/serializers/workflow_run_action.py
lib/workload/stateless/stacks/workflow-manager/workflow_manager/tests/test_viewsets.py
lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/workflow_run_action.py

Add duplication input check before executing emitting rerun events to EB. The check is based on the `READY` state payload, where the workflow entity and linked library are the same as the given wfl_run. The payload check will depend on each wfl type, whereas RNAsum is only based on dataset input.
This will throw an error on UI as the bad request is returned.
closes #815

Feat(WFM): Duplication rerun check

---

lib/workload/stateless/stacks/metadata-manager/app/management/commands/clean_duplicated_libraries.py
lib/workload/stateless/stacks/metadata-manager/deploy/construct/lambda-django-command/index.ts
lib/workload/stateless/stacks/metadata-manager/deploy/construct/lambda-django-command/lambda.Dockerfile
lib/workload/stateless/stacks/metadata-manager/deploy/stack.ts
lib/workload/stateless/stacks/metadata-manager/handler/django_command.py
lib/workload/stateless/stacks/metadata-manager/proc/service/utils.py
lib/workload/stateless/stacks/metadata-manager/proc/tests/test_tracking_sheet_srv.py

- Trim `_rerun` and `_topup` lambda
- Add Django command to cleanup library id with `_rerun` and `_topup`
- A new lambda to able to invoke the Django command above
Resolve #865

Feat(MM): Dedup `topup` / `rerun` Libraries && Cleanup Script

---

lib/workload/stateless/stacks/filemanager/docs/API_GUIDE.md
lib/workload/stateless/stacks/filemanager/filemanager/src/queries/mod.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/queries/update.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/routes/update.rs

Closes #881 
* Allows updating ingest id even if already set, or removing an existing ingest id.

feat(filemanager): allow updating ingest id even if already set

---

lib/workload/stateless/stacks/filemanager/deploy/constructs/functions/function.ts

This is related to failing filemanager builds on CodeBuild: https://github.com/umccr/orcabus/actions/runs/13912874550/job/38930505126?pr=912
I think this is an upstream issue - the `RustFunction` uses zig underneath to cross compile because the native cross compilation using `cargo` is not as convenient. This only occurs on some targets and I think this issue is related: https://github.com/ziglang/zig/issues/23052
Either way, this is only affecting compilation with zig to `aarch64` from an arm64 machine. For that case, it's better to just use cargo directly as there is no cross compilation.
* Fixes the arm64 filemanager builds by avoiding `cargo-zigbuild` and just using cargo directly.

fix: avoid cross compiling on same architecture

---

lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/models/sequence.py
lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/viewsets/sequence_run_stats.py
lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/viewsets/state.py

solve: #879 
Add state operations in the SRM states.
State creation:
Post - `/api/v1/sequence/{orcabus_id}/state/`
update the comment
Patch - `/api/v1/sequence/{orcabus_id}/state/{id}` 
currently it only support 'RESOLVED' for failed sequence run.
```
valid_states_map = {
'RESOLVED': ['FAILED']
}
```

Add srm state operations and apis

---

.gitpod.yml
Makefile
lib/pipeline/statefulPipelineStack.ts
lib/pipeline/statelessPipelineStack.ts
lib/workload/stateful/stacks/postgres-manager/Makefile

By removing the .yarn/yarn--version.cjs file I think corepack enable is needed order for the build commands to work - see 
https://umccr.slack.com/archives/C070B52CHT9/p1743493591199569?thread_ts=1743387409.116639&cid=C070B52CHT9

Enable corepack before all yarn --install commands

---

lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager_proc/services/sequence_srv.py

modify logic rules for status_changed,
status_changed to be true if:
- new sequence is created
- sequence status has changed and current sequence status is not SequenceStatus.SUCCEEDED (SequenceStatus.SUCCEEDED means sequence run is succeeded, any failed or aborted state after that is coming from analysis stage which is not relevant to this sequence run)

Fix - (SRM) ignore status changed after sequece run succeed

---

config/stacks/shared.ts
lib/workload/stateful/stacks/shared/constructs/database/index.ts
lib/workload/stateless/stacks/filemanager/database/Dockerfile
lib/workload/stateless/stacks/metadata-manager/Makefile
shared/mock-db.yml

As we discussed in security patrol, our orcabus version is bit lag behind.
"_Your database resources aren't running the latest minor DB engine version. The latest minor version contains the latest security fixes and other improvements._"
so it is time to upgrade postgres to latest version (include testing postgres images).
After testing in DEV, we can upgrade from 15.4 to 16.6 for orcabus databse engine. And it works fine for all ui api call.
As logs show, there will be around 11 mins downtime for this upgrade. ([log link](https://843407916570-ykjyha5d.ap-southeast-2.console.aws.amazon.com/rds/home?region=ap-southeast-2#database:id=orcabus-db;is-cluster=true;tab=logs-and-events))
But more testing still need to be done.

upgrade orcabus to postgres 16

---

package.json
yarn.lock

Fixes pre-commit-lint-security step and issues with duplicate sfn outputs. With 2.187.0 a `cdk synth` would fail with:
```
ValidationError: Stage Assets.2 already contains an action with name 'sfn_configure_outputs_json_DefinitionBody2'
at path [OrcaBusStatelessPipeline/Pipeline/Pipeline/Assets.2] in constructs.Construct     
```
Related issue https://github.com/aws/aws-cdk/issues/34027

bump: cdk from 2.187.0 to 2.189.0

---

config/config.ts
config/constants.ts
config/stacks/fastqSyncManager.ts
lib/workload/stateful/stacks/fastq-sync-dynamodb/Readme.md
lib/workload/stateful/stacks/fastq-sync-dynamodb/deploy/stack.ts
lib/workload/stateful/statefulStackCollectionClass.ts
lib/workload/stateless/stacks/fastq-sync/Readme.md
lib/workload/stateless/stacks/fastq-sync/deploy/index.ts
lib/workload/stateless/stacks/fastq-sync/deploy/interfaces.ts
lib/workload/stateless/stacks/fastq-sync/lambdas/check_fastq_set_id_against_requirements_py/check_fastq_set_id_against_requirements.py
lib/workload/stateless/stacks/fastq-sync/lambdas/get_fastq_list_row_and_requirements_py/get_fastq_list_row_and_requirements.py
lib/workload/stateless/stacks/fastq-sync/lambdas/get_fastq_list_row_ids_from_fastq_set_id_py/get_fastq_list_row_ids_from_fastq_set_id.py
lib/workload/stateless/stacks/fastq-sync/lambdas/get_fastq_set_ids_from_fastq_list_row_ids_py/get_fastq_set_ids_from_fastq_list_row_ids.py
lib/workload/stateless/stacks/fastq-sync/lambdas/launch_requirement_job_py/launch_requirement_job.py
lib/workload/stateless/stacks/fastq-sync/layers/fastq_sync_tools_layer/pyproject.toml
lib/workload/stateless/stacks/fastq-sync/layers/fastq_sync_tools_layer/src/fastq_sync_tools/__init__.py
lib/workload/stateless/stacks/fastq-sync/layers/fastq_sync_tools_layer/src/fastq_sync_tools/utils/globals.py
lib/workload/stateless/stacks/fastq-sync/layers/fastq_sync_tools_layer/src/fastq_sync_tools/utils/utils.py
lib/workload/stateless/stacks/fastq-sync/layers/index.ts
lib/workload/stateless/stacks/fastq-sync/step_functions_templates/fastq_id_updated.asl.json
lib/workload/stateless/stacks/fastq-sync/step_functions_templates/fastq_set_updated.asl.json
lib/workload/stateless/stacks/fastq-sync/step_functions_templates/initialise_task_token_for_fastq_set_id_sync.asl.json
lib/workload/stateless/stacks/fastq-sync/step_functions_templates/launch_fastq_list_row_requirements.asl.json
lib/workload/stateless/statelessStackCollectionClass.ts

Just added the readme for now
The fastq sync service is a simple service that allows step functions with task tokens to 'hang' 
until the requirements of either a fastq list row or fastq set have been met. 
This is useful for workflow-glue services that have fastq set ids but need to wait for either
1. The fastq set readsets to be created
2. The fastq set to have been qc'd AND have a fingerprint file and compression information
3. This is also useful for data sharing services that require the fastqs to be unarchived before they can be shared
The step function will then hang at that step until the task token has been 'unlocked'
Workflow glue services can use the fastq sync service by generating the following event
```json5
{
"EventBusName": "OrcaBusMain",
"Source": "doesnt matter", …
```

Added Fastq Sync Service

---

lib/workload/stateless/stacks/filemanager/deploy/constructs/functions/api.ts
lib/workload/stateless/stacks/filemanager/filemanager/src/clients/aws/secrets_manager.rs

Related to https://github.com/umccr/orca-ui/issues/173
* Add flag to ignore transient errors in the secrets manager cache.
* Print the error with full context if it does occur.
Hopefully this should reduce the amount of times this occur. I'll have to look into the issue more to determine if it really is a transient error or something else. If it is a transient error and it keeps occuring, I can add a retry mechanism.

fix(filemanager): ignore transient secret errors

---

lib/workload/stateless/stacks/data-sharing-manager/Readme.md
lib/workload/stateless/stacks/data-sharing-manager/scripts/data-sharing-tool.py
lib/workload/stateless/stacks/data-sharing-manager/scripts/install.sh

Added `data-sharing-tool` cli tool for launching fastq manager services.

Added data-sharing manager and toolkit

---

lib/workload/stateless/stacks/data-sharing-manager/scripts/data-sharing-tool.py

Docopt error from --package-name in docs being the first word on a line in the description

Fix list-packages doc=-opt error

---

lib/workload/stateless/stacks/filemanager/database/queries/api/reset_current_state.sql
lib/workload/stateless/stacks/filemanager/database/queries/api/select_existing_by_bucket_key.sql
lib/workload/stateless/stacks/filemanager/filemanager/src/database/aws/ingester.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/queries/list.rs

Closes #989
* Order nulls last when descending and first when ascending to fix null sequencers being preferred over real sequencers.

fix(filemanager): order nulls last desc and first asc to preserve correct current state

---

lib/workload/stateless/stacks/fastq-glue/deploy/index.ts
lib/workload/stateless/stacks/fastq-glue/deploy/interfaces.ts
lib/workload/stateless/stacks/fastq-glue/lambdas/get_sample_demultiplex_stats_py/get_sample_demultiplex_stats.py
lib/workload/stateless/stacks/fastq-glue/step_functions_templates/fastq_set_add_read_set_template_sfn.asl.json

Fastq glue now creates 'empty' fastq list rows when srm completes and then adds readsets once bsshfastqcopy completes.

Fastq glue should listen to SRM succeeded events

---

config/constants.ts
config/stacks/fileManager.ts
config/stacks/fmAnnotator.ts
config/stacks/htsget.ts
lib/workload/components/api-gateway/index.ts
lib/workload/stateless/stacks/fmannotator/deploy/stack.ts
lib/workload/stateless/stacks/htsget/stack.ts
lib/workload/stateless/statelessStackCollectionClass.ts
package.json
yarn.lock

* Removes direct stack-based dependency on filemanager from htsget and fmannotator.
* Update htsget-rs construct dependency to support `IRole` instead of `Role`.
I need to remove this because otherwise when migrating filemanager to the new [repo](https://github.com/OrcaBus/service-filemanager), I can't update the new stack because CloudFormation expects that the FileManager stack exports variables for the domain name and ingest role. This way, the dependency is more loosely coupled (with constants/parameters) so it won't refuse to update in CloudFormation.
This shouldn't result in any changes to the behaviour of the services.

refactor(stateless): detach direct dependency on the filemanager stack

---

lib/workload/stateful/statefulStackCollectionClass.ts

* Removes the access key secret stack as it will be managed by the filemanager stateful stack: https://github.com/OrcaBus/service-filemanager/blob/main/infrastructure/stage/filemanager-stateful-stack.ts

refactor(platform): remove access key secret stack

---

config/stacks/schema/events.ts
docs/schemas/events/sequencerunmanager/Makefile
docs/schemas/events/sequencerunmanager/SequenceRunLibraryLinkingChange.schema.json
docs/schemas/events/sequencerunmanager/SequenceRunSampleSheetChange.schema.json
docs/schemas/events/sequencerunmanager/example/SRLLC.json
docs/schemas/events/sequencerunmanager/example/SRSSC.json

As description, SRLLC and SRSSC events need to been added to eventbus.
```
{
"version": "0",
"id": "12345678-90ab-cdef-1234-567890abcdef",
"detail-type": "SequenceRunLibraryLinkingChange",
"source": "orcabus.sequencerunmanager",
"account": "000000000000",
"time": "2025-03-00T00:00:00Z",
"region": "ap-southeast-2",
"resources": [],
"detail": {
"instrumentRunId": "123456_A7890_1234_ABCDEFGH",
"sequenceRunId": "r.1234567890abcdefghijklmn",
"sequenceRunOrcabusId": "seq.1234567890ABCDEFGHIJKLMN",
"timeStamp": "2025-03-01T00:00:00.123456Z",
"linkedLibraries": [
"L2000000",
"L2000001",
"L2000002"
]
}
}
```
```
{
"version": "0",
"id": "12345678-90ab-cdef-1234-567890abcdef",
"detail-type": "SequenceRunSampleSheetChange",
"source": "orcabus.sequencerunmanager",
"account": "000000000000",
"time": …
```

add srllc and srssc events

---

lib/workload/stateful/statefulStackCollectionClass.ts
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/handy-pal/index.ts
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/handy-pal/part_1/initialise-wts-and-wgs-libraries/index.ts
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/handy-pal/part_2/populate-fastq-list-rows/index.ts
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/index.ts
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/jb-weld/index.ts
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/jb-weld/part_1/initialise-cttsov2-library-dbs/index.ts
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/jb-weld/part_2/populate-fastq-list-row-dbs/index.ts
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/jb-weld/part_3/fastq-list-row-event-shower-complete-to-cttsov2-ready/index.ts
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/kwik/index.ts
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/kwik/part_1/initialise-wgts-library-dbs/index.ts
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/kwik/part_2/populate-fastq-list-row-dbs/index.ts
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/kwik/part_3/fastq-list-rows-shower-complete-to-wgts-qc/index.ts
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/kwik/part_4/push-fastq-list-row-qc-complete-event/index.ts
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/kwik/part_5/library-qc-complete-event/index.ts
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/loctite/index.ts
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/loctite/part_1/initialise-tn-library-dbs/index.ts
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/loctite/part_2/update-fastq-list-rows-dbs/index.ts
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/mod-podge/index.ts
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/mod-podge/part_1/initialise-wts-library-dbs/index.ts
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/mod-podge/part_2/update-fastq-list-rows-dbs/index.ts
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/nails/index.ts
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/nails/part_1/initialise-library-db/index.ts
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/pva/index.ts
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/pva/part_1/initialise-umccrise-library-dbs/index.ts
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/roket/index.ts
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/roket/part_1/initialise-rnasum-library-dbs/index.ts
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/t-rex/index.ts
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/t-rex/part_1/initialise-wts-wgs-libraries/index.ts
lib/workload/stateless/statelessStackCollectionClass.ts

Clag services now part of the fastq glue stack
* Update downstream stacky services to listen to new events from fastqglue stack instead.
* Renamed FastqListRowStateChange events to StackyFastqListRowStateChange events
* Deprecate the following stacks:
* bsshIcav2FastqCopyManagerStack - replaced by bssh-fastq-to-aws-s3 copy manager stack in new repo
* bclconvertInteropQcIcav2PipelineManagerStack - replaced by bclconvert-interop-qc-stack in new repo
* fastqGlueStack - replaced by fastq-glue stack in new repo

Detach primary data services

---

lib/workload/stateless/stacks/fastq-unarchiving/app/step_functions_templates/run_s3_steps_copy_sfns_sfn_template.asl.json

Fastq manager lambdas might retain invalid cached data, wait 15 minutes before releasing event to say unarchived data is available

Just wait 15 minutes before releasing event

---

lib/workload/stateful/stacks/data-sharing-s3-and-db/deploy/stack.ts
lib/workload/stateful/statefulStackCollectionClass.ts
lib/workload/stateless/statelessStackCollectionClass.ts

Replaced by https://github.com/OrcaBus/service-fastq-sync-manager and https://github.com/OrcaBus/service-fastq-unarchiving-manager

Deprecate unarchiving and sync manager stacks, migrated to separate repos
