Makefile
README.md
bin/orcabus.ts
bin/pipeline.ts
config/constants.ts
lib/pipeline/orcabus-pipeline-stack.ts
package.json

* Dropped make build step as it will be part of cdk synth
* Improved README and typography

Updated pipeline to use UMCCR AWS accounts

---

docs/developer/DJANGO_API.md
docs/developer/DJANGO_PROC.md
skel/django-api/src/project_name/models/base.py
skel/django-api/src/project_name/models/helloworld.py
skel/django-api/src/project_name/settings/base.py
skel/django-api/src/project_name/tests/test_base.py
skel/django-api/src/requirements.txt
skel/django-proc/src/project_name/settings/base.py
skel/django-proc/src/requirements.txt

* Isolated microservice app table namespace by table prefix
* Added high level abstract OrcaBusBaseModel and OrcaBusBaseManager for API profile

Improved Django template skel profile

---

config/event_schemas/SequenceRunStateChange.json
docs/developer/SRM.md

* Reduced required properties to minimal and make it "Thin Event"
* Added SRM doc Ready Check section

Improved SequenceRunStateChange Event schema

---

lib/workload/stateless/filemanager/.sqlx/query-3fe88592da137c9706a5b541ef8edb7a794c72051d12c8c3b57d853b37a8392e.json
lib/workload/stateless/filemanager/.sqlx/query-63da484d18ed2571639cfddadf992fe9ea92767a8274859de371f4e954e554b8.json
lib/workload/stateless/filemanager/Makefile
lib/workload/stateless/filemanager/README.md

fix(filemanager): re-run sqlx prepare with all targets

---

lib/workload/stateless/sequence_run_manager/deploy/component.ts

Fixed SequenceRunManager architecture to ARM64

---

lib/workload/stateless/sequence_run_manager/compose.yml
lib/workload/stateless/sequence_run_manager/deps/requirements-dev.txt
lib/workload/stateless/sequence_run_manager/deps/requirements-test.txt
lib/workload/stateless/sequence_run_manager/deps/requirements.txt
lib/workload/stateless/sequence_run_manager/sequence_run_manager/settings/base.py

Trimmed down the sequence_run_manager

---

lib/workload/stateless/sequence_run_manager/api.py
lib/workload/stateless/sequence_run_manager/deploy/apigw/component.ts
lib/workload/stateless/sequence_run_manager/deploy/component.ts
lib/workload/stateless/sequence_run_manager/sequence_run_manager/urls/base.py
lib/workload/stateless/sequence_run_manager/sequence_run_manager/urls/local.py
skel/django-api/src/api.py

Improved sequence_run_manager API Gateway setup

---

lib/workload/orcabus-stateless-stack.ts
lib/workload/stateless/filemanager/deploy/constructs/functions/function.ts
lib/workload/stateless/filemanager/deploy/constructs/functions/ingest.ts
lib/workload/stateless/filemanager/deploy/constructs/functions/migrate.ts
lib/workload/stateless/filemanager/deploy/lib/filemanager.ts

Related to #196 and #138
* Slight rearrange of filemanager props.
* Reconstruct SSM parameter in filemanager to avoid test errors.

fix(filemanager): ssm parameter in tests

---

lib/workload/stateful/token_service/deploy/construct/policy/index.ts
lib/workload/stateful/token_service/deploy/stack.ts

* Minor refactor policy statement into dedicated policy construct
* Lambda within a VPC need VPC related Ec2 policy

Added Token Service policy construct

---

lib/workload/stateful/token_service/README.md
lib/workload/stateful/token_service/deploy/construct/policy/index.ts

* The key `conditions` is not array
* Added ica_credential ref pointer

Fixed Token Service policy syntax

---

lib/workload/stateful/token_service/Makefile
lib/workload/stateful/token_service/README.md
lib/workload/stateful/token_service/token_service/cognitor/tests.py
lib/workload/stateful/token_service/token_service/rotate_service_jwt.py
lib/workload/stateful/token_service/token_service/rotate_service_user.py

* Improved README, Makefile and local DX

Fixed Token Service Python import arrangement

---

lib/workload/stateful/token_service/deploy/stack.ts
lib/workload/stateful/token_service/token_service/rotate_service_jwt.py
lib/workload/stateful/token_service/token_service/rotate_service_user.py

* Removed static endpoint lookup requirement from
boto client bootstrapping

Fixed Token Service initial value json parsing

---

test/stateful/databaseConstruct.test.ts

fix improper vpc construct used for testing

Fix Stateful Test

---

config/constants.ts
config/stacks/icaEventPipe.ts
lib/workload/stateful/stacks/ica-event-pipe/constructs/ica_event_pipe/index.ts
lib/workload/stateful/stacks/ica-event-pipe/stack.ts
test/stateful/ica-event-pipe/icaEventPipeConstruct.test.ts

Add sns:SendMessage permissions to incoming queue
Update tests to check for additional permissions
Refactor construct directory name to constructs

Update SQS policy to allow ICA to send notifications.

---

config/constants.ts
config/stacks/metadataManager.ts
lib/workload/stateless/stacks/metadata-manager/deploy/README.md
lib/workload/stateless/stacks/metadata-manager/deploy/construct/lambda-api/index.ts
lib/workload/stateless/stacks/metadata-manager/deploy/construct/lambda-migration/index.ts
lib/workload/stateless/stacks/metadata-manager/deploy/stack.ts
lib/workload/stateless/stacks/metadata-manager/handler/migrate.py

- Fix API GW for API Lambda
- Add provider custom resource for migration lambda

fix(metadata-manager): Fix API GW && Custom Resource for Migration Lambda

---

config/stacks/schema.ts
docs/event-schemas/srm/SequenceRunStateChange.json
docs/event-schemas/wfm/WorkflowRunStateChange.json
docs/event-schemas/wfm/example/WRSC__bct__bssh_bcl_convert.json
docs/event-schemas/wfm/example/WRSC__fqcp__bssh_icav2_fastq_copy.json
docs/event-schemas/wfm/example/WRSC__wfm__bssh_icav2_fastq_copy.json

* Use opaque Payload object for differing workflow type
* Introduce two workflow types: `bssh_icav2_fastq_copy` and `bssh_bcl_convert`
* Introduce 3 namespaces for services: `orcabus.wfm`, `orcabus.bct`, `orcabus.fqcp`

Implemented WorkflowRunStateChange schema

---

lib/pipeline/statelessPipelineStack.ts

Resolves https://github.com/umccr/orcabus/issues/285 (in theory)

Remove cdk.out assets to prevent synth output

---

lib/workload/stateless/stacks/bs-runs-upload-manager/Readme.md
lib/workload/stateless/stacks/bs-runs-upload-manager/step_functions_templates/bs_runs_upload_step_functions_template.json
lib/workload/stateless/stacks/sequence-run-manager/Makefile
lib/workload/stateless/stacks/sequence-run-manager/deps/requirements-test.txt
lib/workload/stateless/stacks/sequence-run-manager/deps/requirements.txt
lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/settings/base.py
lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager_proc/domain/sequence.py
lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager_proc/domain/sequencerunstatechange/AWSEvent.py
lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager_proc/domain/sequencerunstatechange/SequenceRunStateChange.py
lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager_proc/domain/sequencerunstatechange/marshaller.py
lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager_proc/tests/test_sequence_domain.py

* Updated SequenceRunStateChange schema code binding from Schema Registry
* Added djangorestframework-camel-case to automate snake_case to camelCase
Resolves #276

Updated SequenceRunManager service to align with SequenceRunStateChange

---

.github/workflows/prbuild.yml
README.md
docs/developer/DJANGO_API.md

As discussed, do not run GH Action test on draft-pr

Feat: Limit PR Testing

---

config/config.ts
config/constants.ts
config/stacks/schema/data.ts
config/stacks/schema/events.ts
config/stacks/shared.ts
docs/schemas/README.md
docs/schemas/data/bsshicav2fastqcopymanager/PayloadDataReady.json
docs/schemas/data/bsshicav2fastqcopymanager/PayloadDataSucceeded.json
lib/workload/stateful/stacks/shared/stack.ts
lib/workload/stateless/stacks/schema/README.md
lib/workload/stateless/statelessStackCollectionClass.ts
test/stateful/shared/schemaRegistryConstruct.test.ts

* Updated corresponding README and guide
Resolves #257

Added data schema registry and data schema deployment stack

---

lib/workload/stateless/stacks/bclconvert-manager/deps/requirements.txt
lib/workload/stateless/stacks/bclconvert-manager/translator_service/icav2_event_translator.py

Updated v2-samplesheet-maker to handle tso500L headers with new regex. 
Also reformatted python file and added example execution.

update translator service to bclconvert manager

---

lib/workload/stateful/stacks/bclconvert-dynamo-db/README.md
lib/workload/stateless/stacks/bclconvert-manager/README.md

1. update docs for bcl convert manger data
2. re-trigger the whole pipeline

update docs for bcl convert manger data

---

lib/workload/stateless/stacks/bclconvert-manager/README.md
lib/workload/stateless/stacks/bclconvert-manager/translator_service/icav2_event_translator.py
lib/workload/stateless/stacks/bclconvert-manager/translator_service/tests/test_icav2_event_translator.py

1.  fix bugs for non-succeed event, as Non-SUCCEEDED event will not carry payload
2. update unit test to include both Non-SUCCEEDED and SUCCEEDED Event testing

fix bugs for non-succeed event and update unit

---

config/constants.ts
config/stacks/bsRunsUploadManager.ts
lib/workload/stateless/stacks/bs-runs-upload-manager/deploy/constructs/bs-runs-upload-manager/index.ts
lib/workload/stateless/stacks/bs-runs-upload-manager/deploy/stack.ts
lib/workload/stateless/stacks/bs-runs-upload-manager/lambdas/launch_bs_runs_upload_tes/handler.py
lib/workload/stateless/stacks/bs-runs-upload-manager/lambdas/upload_v2_samplesheet_to_gds_bssh/handler.py
lib/workload/stateless/stacks/bs-runs-upload-manager/layers/src/bs_runs_upload_manager_tools/utils/aws_ssm_helpers.py
lib/workload/stateless/stacks/bs-runs-upload-manager/layers/src/bs_runs_upload_manager_tools/utils/portal_helpers.py
lib/workload/stateless/stacks/bs-runs-upload-manager/layers/src/bs_runs_upload_manager_tools/utils/samplesheet_helpers.py

* Also use 'currentVersion' attribute when specifying functionArns
Resolves  https://github.com/umccr/orcabus/issues/265

Updated the sscheck api url from the ssm parameter

---

lib/workload/stateless/stacks/bclconvert-manager/translator_service/icav2_event_translator.py

fix generate-db-uuid params issue

fix generate-db-uuid params issue

---

.gitignore
cdk.context.json

Just as we discussed, add `cdk.context.json` to our project  avoid non-deterministic behavior.
Refer: [Commit cdk.context.json to avoid non-deterministic behavior](https://docs.aws.amazon.com/cdk/v2/guide/best-practices.html#best-practices-apps)

Fix: add-CDK-context-for-role-assumption-across-accounts

---

config/constants.ts
lib/workload/components/dynamodb-icav2-ready-event-handler-sfn/Readme.md
lib/workload/stateless/stacks/bclconvert-interop-qc-pipeline-manager/Readme.md
lib/workload/stateless/stacks/bclconvert-interop-qc-pipeline-manager/scripts/trigger_bclconvert_interop_qc.sh
lib/workload/stateless/stacks/bclconvert-interop-qc-pipeline-manager/step_functions_templates/set_bclconvert_interop_qc_cwl_inputs_sfn.asl.json
lib/workload/stateless/stacks/cttso-v2-pipeline-manager/Readme.md
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/selleys/constructs/part_3/bclconvert-interopqc-input-maker/step_function_templates/generate_interopqc_event_maker.asl.json

Use instrument run id instead of run id for bclconvert interop qc pipeline

---

lib/workload/stateless/stacks/filemanager/filemanager/src/error.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/queries/list.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/routes/list.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/routes/mod.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/routes/openapi.rs

Closes #391
* Add pagination to `/s3_objects` and `/objects` and associated tests.

feat: filemanager pagination

---

lib/workload/components/dynamodb-icav2-ready-event-handler-sfn/step_functions_templates/icav2_launch_workflow_and_raise_internal_event.asl.json

Resolves https://github.com/umccr/orcabus/issues/431

Wrap launch analysis step function segment into a parallel chunk to reduce step output sizes

---

lib/workload/stateless/stacks/cttso-v2-pipeline-manager/deploy/stack.ts

Fixed cttsov2 post-processing docker architecture ARM_64

---

config/constants.ts

Update ssm parameter pipeline constants for new icav2 pipelines

---

lib/workload/stateless/stacks/workflow-manager/workflow_manager/models/base.py
lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/payload.py
lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/workflow.py
lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/workflow_run.py

* This reinstate API request query parameter filter by each viewsets field attribute including FK linked model fields.

Fixed Workflow Manager API filter by attributes

---

compose.yml
lib/workload/stateless/stacks/metadata-manager/app/settings/base.py
lib/workload/stateless/stacks/metadata-manager/app/tests/test_viewsets.py
lib/workload/stateless/stacks/metadata-manager/app/urls/base.py
lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/urls/base.py
lib/workload/stateless/stacks/workflow-manager/workflow_manager/models/base.py
lib/workload/stateless/stacks/workflow-manager/workflow_manager/urls/base.py
lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/payload.py
lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/workflow.py
lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/workflow_run.py

This will harmonise API base URL into:
```
https://metadata.dev.umccr.org/api/v1/
https://sequence.dev.umccr.org/api/v1/
https://workflow.dev.umccr.org/api/v1/
https://file.dev.umccr.org/api/v1/
```

Harmonised API v1 versioning namespace base URL

---

.github/workflows/prbuild.yml

* Check also PR title contain `[draft]` tag

[skip ci]: Updated GH prbuild.yml

---

.github/workflows/prbuild.yml

* Expression need to evaluate False either side to skip GH Action check.
i.e. Either PR created with Draft mode or, contain "[draft]" tag.

[skip ci]: Fixed GH prbuild.yml

---

.github/dependabot.yml
.prettierignore

* Append commit message prefix with [draft] tag initially.
We shall review PR then figure whether proceed trigger
running ci build or skip otherwise.

[draft]: Added dependabot.yml config file

---

lib/workload/stateful/stacks/postgres-manager/deploy/lambda-build.Dockerfile
lib/workload/stateful/stacks/postgres-manager/package.json
lib/workload/stateful/stacks/postgres-manager/yarn.lock

Bumped PGM dependencies

---

lib/workload/stateless/stacks/metadata-manager/app/settings/local.py
lib/workload/stateless/stacks/metadata-manager/app/viewsets/lab.py
lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/settings/local.py
lib/workload/stateless/stacks/workflow-manager/workflow_manager/settings/local.py
lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/library.py

Some settings on DRF-Spectacular to convert the snake_case to camelCase

Fix Django OpenAPI Schema

---

lib/workload/stateless/stacks/workflow-manager/workflow_manager/management/commands/generate_mock_workflow_run.py
lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/workflow_run.py

- Add ongoing endpoint to allow listing of non-terminal workflow runs
- Update mock data to include non-terminal workflow run states

WFM - Extend API capabilities - ongoing workflowrun filter

---

lib/workload/stateless/stacks/metadata-manager/handler/sync_tracking_sheet.py
lib/workload/stateless/stacks/metadata-manager/proc/service/tracking_sheet_srv.py

* Standardise year to string value internally

Fixed metadata sheet processing year input data type

---

lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/jb-weld/part_4/fastq-list-row-event-shower-complete-to-cttsov2-draft/lambdas/build_cttsov2_samplesheet_py/build_cttso_v2_samplesheet.py

Ilmn Tech support number: 03973338

TSO500L Data shouldn't have lane data

---

lib/workload/stateless/stacks/filemanager/Dockerfile

fix(filemanager): swap docker hub images for AWS public ECR

---

lib/workload/stateless/stacks/workflow-manager/workflow_manager/management/commands/generate_mock_workflow_run.py
lib/workload/stateless/stacks/workflow-manager/workflow_manager/models/state.py
lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/workflow_run.py

Addresses https://github.com/umccr/orcabus/issues/593

Add RESOLVED state as supported WorkflowRun state

---

lib/workload/stateless/stacks/workflow-manager/workflow_manager/serializers/state.py
lib/workload/stateless/stacks/workflow-manager/workflow_manager/serializers/workflow.py
lib/workload/stateless/stacks/workflow-manager/workflow_manager/serializers/workflow_run.py
lib/workload/stateless/stacks/workflow-manager/workflow_manager/urls/base.py
lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/state.py
lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/workflow_run.py

Update  and modification for some related attributes of workflow runs  for ui,
couple with https://github.com/umccr/orca-ui/pull/52, for ui fix.

wfm update for ui fix

---

lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/gorilla/part_1/bclconvert-interop-qc-draft-event-maker/step_functions_templates/generate_bclconvert_interop_qc_draft_event_sfn_template.asl.json

Updated linked libraries json path

Updated json paths for portal run id and workflow run name

---

lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/roket/part_2/umccrise-and-wts-complete-to-rnasum-draft/step_functions_templates/umccrise_and_wts_complete_to_rnasum_draft.asl.json

Didn't quite patch it properly in #630

Need to collect camelCase orcabus Id when retrieving object from metadata manager

---

lib/workload/components/icav2-copy-files/check_or_launch_job_lambda_py/check_or_launch_job_lambda.py
lib/workload/components/icav2-copy-files/step_functions_templates/copy_files_sfn.asl.json

Also increase retry copy failure up to ten times. 
Doesn't fix everything, particularly when ICAv2 is completely broken but it helps rule out any issues from residual files sticking around.

Delete partial files before retrying copy job

---

lib/workload/components/ora-file-decompression-fq-pair-sfn/tasks/ora_decompression/Dockerfile

Download files from GitHub instead
Resolves #641

CodeBuild doesn't support git-lfs

---

lib/workload/components/sfn-icav2-ready-event-handler/icav2_launch_pipeline_lambda_py/icav2_launch_pipeline_lambda.py
lib/workload/components/sfn-icav2-ready-event-handler/index.ts
lib/workload/components/sfn-icav2-ready-event-handler/step_functions_templates/icav2_launch_workflow_and_raise_internal_event.asl.json
lib/workload/stateless/stacks/ora-compression-manager/deploy/index.ts

One day will allow for per-run
Resolves #637

Add analysis size option per microservice

---

lib/workload/components/icav2-copy-files/check_or_launch_job_lambda_py/check_or_launch_job_lambda.py

Resolves discussion in https://github.com/umccr-illumina/ica_v2/issues/208

Manually transfer files that are smaller than 8 MiB or dont have an etag

---

lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/jb-weld/part_1/initialise-cttsov2-library-dbs/index.ts

Prevent the ntc samples running through cttsov2

---

lib/workload/components/sfn-nf-batch-ready-event-handler/step_functions_templates/launch_nextflow_pipeline_template.asl.json

* This is pretty much static status initially as persisting
into DynamoDB table step.

Fixed oncoanalyser Batch trigger initial status SUBMITTED

---

lib/workload/components/sfn-nf-batch-ready-event-handler/index.ts

Resolves https://github.com/umccr/orcabus/issues/672

Wrong typescript boolean logic which meant there was no event rule

---

lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/handy-pal/part_3/launch-oncoanalyser-ready-events/lambdas/generate_dna_payload_py/generate_dna_payload.py
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/handy-pal/part_3/launch-oncoanalyser-ready-events/lambdas/generate_rna_payload_py/generate_rna_payload.py
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/t-rex/part_2/oncoanalyser-dna-complete-to-sash-ready/lambdas/generate_sash_payload_py/generate_sash_payload.py
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/t-rex/part_3/oncoanalyser-dna-or-rna-to-oncoanalyser-both-ready/lambdas/get_oncoanalyser_dna_rna_payload_py/get_oncoanalyser_dna_rna_payload.py

Sanitise subject id for oncoanalyser / sash / nf workflows

---

lib/workload/stateless/stacks/bclconvert-manager/deps/requirements.txt
lib/workload/stateless/stacks/cttso-v2-pipeline-manager/lambdas/upload_samplesheet_to_cache_dir_py/requirements.txt

Update v2 samplesheet maker version

---

lib/workload/components/sfn-nf-batch-state-change-event-handler/step_functions_templates/capture_aws_batch_completion_events_template.asl.json

Fix status for non-terminal

---

config/constants.ts
config/stacks/rnasumPipelineManager.ts
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/roket/part_2/umccrise-and-wts-complete-to-rnasum-draft/index.ts

See pipeline id from https://github.com/umccr/cwl-ica/releases/tag/rnasum-pipeline%2F1.1.5__20241112044604
Supersedes #675
Resolves #676

Update rnasum pipeline version to 1.1.5

---

lib/workload/stateless/stacks/rnasum-pipeline-manager/deploy/index.ts

EVENT_BUS_NAME env var needs to be added to lambda env var

Fix rnasum rerun lambda

---

lib/workload/stateless/stacks/metadata-manager/app/viewsets/library.py

- Update Query Params gte and lte syntax
- Add ProjectId for filter
Resolves https://github.com/umccr/orca-ui/issues/83

Feat(mm): Allow Library Filtered by Project

---

lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/jb-weld/part_1/initialise-cttsov2-library-dbs/index.ts

Set sample type to ctDNA for cttsov2 triggers

---

lib/workload/stateless/stacks/ora-compression-manager/step_functions_templates/rate_limit_get_raw_md5sum_for_fastq_gzip_sfn_template.asl.json
lib/workload/stateless/stacks/ora-compression-manager/step_functions_templates/rate_limit_get_raw_md5sum_for_fastq_ora_sfn_template.asl.json

Sleep command should then loop to list-executions

---

lib/workload/stateless/stacks/data-migrate/deploy/stack.ts

Related to #726
* Use ARM64 instead of X86_64.

fix(data-migrate): set arch as ARM64

---

lib/workload/components/gzip-raw-md5sum-fq-pair-sfn/step_functions_templates/get_raw_md5sum_for_fastq_gzip_pair_template.asl.json
lib/workload/components/ora-file-decompression-fq-pair-sfn/step_functions_templates/decompress_ora_fastq_pair_sfn_template.asl.json
lib/workload/stateless/stacks/ora-compression-manager/lambdas/find_all_fastq_pairs_in_instrument_run_py/find_all_fastq_pairs_in_instrument_run.py
lib/workload/stateless/stacks/ora-compression-manager/lambdas/find_all_v2_samplesheets_in_instrument_run_py/find_all_v2_samplesheets_in_instrument_run.py
lib/workload/stateless/stacks/ora-compression-manager/step_functions_templates/get_raw_md5sum_for_all_fastq_gzips_sfn_template.asl.json
lib/workload/stateless/stacks/ora-compression-manager/step_functions_templates/set_compression_inputs.asl.json

And single read libraries
Resolves #727 and #728

ORA Compression fixes for too large sfns, single indexed libraries

---

lib/workload/stateless/stacks/ora-compression-manager/step_functions_templates/set_compression_inputs.asl.json

Use hash for cache uri

---

lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/jb-weld/part_4/launch-holmes-extract-event/step_functions_templates/cttsov2_complete_to_holmes_bam_extraction_sfn_template.asl.json
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/kwik/part_6/launch-holmes-extract-event/step_functions_templates/holmes_extract_wrapper_sfn_template.asl.json

Update holmes glue wrappers to match new input syntax

---

lib/workload/stateless/stacks/ora-compression-manager/step_functions_templates/get_raw_md5sum_for_all_fastq_ora_sfn_template.asl.json

Fix map output size limit error, also set partition size to 50

Fix map output size limit

---

lib/workload/stateless/stacks/tumor-normal-pipeline-manager/Readme.md
lib/workload/stateless/stacks/tumor-normal-pipeline-manager/docs/ready_data_schema.json

Certainly incomplete, and need to provide an example for a library that actually exists in production

Added readme for launching the tumor normal pipeline

---

lib/workload/stateless/stacks/transcriptome-pipeline-manager/step_functions_templates/set_wts_cwl_inputs_sfn.asl.json

Fix step functions where next attribute for Merge Boolean Skipped new step

---

lib/workload/stateless/stacks/workflow-manager/workflow_manager/management/commands/generate_analysis_for_metadata.py
lib/workload/stateless/stacks/workflow-manager/workflow_manager/models/utils.py
lib/workload/stateless/stacks/workflow-manager/workflow_manager/tests/test_models.py

Fix incorrect `portal_run_id` format

Fix(WFM): Portal Run Id Creation

---

lib/workload/stateless/stacks/cttso-v2-pipeline-manager/step_functions_templates/set_cttso_v2_nf_inputs.asl.json
lib/workload/stateless/stacks/filemanager/deploy/stack.ts
lib/workload/stateless/stacks/filemanager/filemanager-api-server/src/main.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/routes/error.rs
lib/workload/stateless/stacks/filemanager/filemanager/src/routes/openapi.rs
lib/workload/stateless/stacks/htsget/stack.ts
lib/workload/stateless/stacks/metadata-manager/app/settings/base.py
lib/workload/stateless/stacks/metadata-manager/app/settings/local.py
lib/workload/stateless/stacks/metadata-manager/app/urls/base.py
lib/workload/stateless/stacks/metadata-manager/app/urls/local.py
lib/workload/stateless/stacks/metadata-manager/deploy/construct/lambda-api/index.ts
lib/workload/stateless/stacks/sequence-run-manager/deploy/stack.ts
lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/settings/base.py
lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/settings/local.py
lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/urls/base.py
lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/urls/local.py
lib/workload/stateless/stacks/workflow-manager/deploy/stack.ts
lib/workload/stateless/stacks/workflow-manager/workflow_manager/management/commands/generate_analysis_for_metadata.py
lib/workload/stateless/stacks/workflow-manager/workflow_manager/models/utils.py
lib/workload/stateless/stacks/workflow-manager/workflow_manager/serializers/base.py
lib/workload/stateless/stacks/workflow-manager/workflow_manager/settings/base.py
lib/workload/stateless/stacks/workflow-manager/workflow_manager/settings/local.py
lib/workload/stateless/stacks/workflow-manager/workflow_manager/tests/test_models.py
lib/workload/stateless/stacks/workflow-manager/workflow_manager/urls/base.py
lib/workload/stateless/stacks/workflow-manager/workflow_manager/urls/local.py
package.json
skel/django-api/deploy/stack.ts
skel/django-api/project_name/settings/base.py
skel/django-api/project_name/settings/local.py
yarn.lock

Release 0.3.1

---

lib/pipeline/component/uiOpenAPITest.ts
lib/pipeline/statelessPipelineStack.ts
lib/workload/stateless/stacks/metadata-manager/app/settings/base.py
lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/settings/base.py
lib/workload/stateless/stacks/workflow-manager/workflow_manager/settings/base.py

It will check the deployed stage API against the [umccr/orca-ui ](https://github.com/umccr/orca-ui)`main` branch. Currently,  setup is the `main` branch is the deployed STG version of the UI.
https://github.com/umccr/orca-ui/issues/97

Feat: Test Deployed OpenAPI Schema with Typescript Type Check

---

lib/pipeline/component/uiOpenAPITest.ts

Fix: OrcaUI Type Testing

---

lib/workload/stateless/stacks/metadata-manager/app/serializers/library.py
lib/workload/stateless/stacks/metadata-manager/app/serializers/subject.py
lib/workload/stateless/stacks/metadata-manager/app/viewsets/library.py
lib/workload/stateless/stacks/metadata-manager/app/viewsets/subject.py

Allow filtering library based on the `SBJXXX` Id.
- Added `individualId` query param in the `/library` and `/subject` endpoint for filter 
- Added `individual_id` and `library_id` to the global search in the Subject endpoint
https://github.com/umccr/orca-ui/issues/132

Feat(MM): Expand Metadata List Filtering

---

config/stacks/sequenceRunManager.ts
lib/workload/stateless/stacks/sequence-run-manager/deploy/stack.ts

just quick fix for orcaUI base url in slack notification.

Fix (SRM) quick fix of the orcaUI base url

---

lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/workflow_run.py
lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/workflow_run_stats.py

solve https://github.com/umccr/orca-ui/issues/155
Fix the duplicate record returned when call workflow api and filter with multiple library_ids
example: `/api/v1/workflowrun/?libraries__libraryId=TSPF-NA12878-10B-Rep1&libraries__libraryId=TSPF-NA12878-10B-Rep2&libraries__libraryId=TSPF-NA12878-10B-Rep3&page=1&rowsPerPage=10`
preview indev:https://orcaui.dev.umccr.org/runs/sequence/seq.01JP9FSH7FPP4050G71CEA92MG/workflowruns?page=1&workflowRunStatus=succeeded

Fix duplicate results from multiple library_ids filter

---

package.json
yarn.lock

Addresses security issue in 2.186.0

bump: cdk from 2.186.0 to 2.187.0

---

lib/workload/stateless/stacks/sample-sheet-check/sample-sheet-check-lambda/src/samplesheet.py
lib/workload/stateless/stacks/sample-sheet-check/sample-sheet-check-lambda/src/v2_samplesheet_builder.py

Fix the sample sheet that has a topup postfix in the `Sample_Name`

Fix(sscheck): Strip topup in library_id

---

lib/workload/stateless/stacks/cttso-v2-pipeline-manager/step_functions_templates/set_cttso_v2_nf_inputs.asl.json

Small error when trying to run down decompressing oras path

Fix ora inputs sfn for cttso workflow input handler

---

package.json

Release notes:
https://github.com/yarnpkg/berry/releases/tag/%40yarnpkg%2Fcli%2F4.9.0
https://github.com/yarnpkg/berry/releases/tag/%40yarnpkg%2Fcli%2F4.9.1

Upgrade yarn version

---

config/constants.ts
config/stacks/fileManager.ts
config/stacks/shared.ts

Future projects will just need to update the list in the constants.ts file.
Resolves #976

Added project montauk and external project buckets object

---

lib/workload/stateless/stacks/fastq-manager/app/api/fastq_manager_api_tools/models/fastq_list_row.py

Date object not set for some fqrs, shouldn't break generating fqlr dicts

---

lib/workload/stateless/stacks/data-sharing-manager/Readme.md
lib/workload/stateless/stacks/data-sharing-manager/scripts/data-sharing-tool.py
lib/workload/stateless/stacks/data-sharing-manager/scripts/install.sh

Added package name to package generation script
Added defrost archived fastqs option

Updated athena docs on data sharing tool

---

lib/workload/stateless/stacks/fastq-manager/app/api/fastq_manager_api_tools/api/v1/routers/fastq_set.py

missed in previous fix for this for one event type - disallowAdditionalFastqs

Dont push s3 details for event

---

Makefile
lib/workload/stateless/statelessStackCollectionClass.ts

chore(MM): Deprecate metadata-manager-stack

---

lib/workload/stateless/statelessStackCollectionClass.ts

* Removes filemanager stack as it's now part of https://github.com/OrcaBus/service-filemanager

refactor(platform): remove filemanager stack

---

lib/workload/components/python-filemanager-tools-layer/filemanager_tools_layer/src/filemanager_tools/utils/request_helpers.py

Unquote next link, otherwise filemanager doesnt process it

---

lib/workload/stateful/statefulStackCollectionClass.ts
lib/workload/stateless/statelessStackCollectionClass.ts

Detach icav2 data copy manager stack

---

lib/workload/stateless/stacks/fastq-sync/step_functions_templates/fastq_set_updated.asl.json

Use minus syntax when removing a string set from a string set

Delete an item from a set using DELETE syntax

---

lib/workload/components/python-filemanager-tools-layer/filemanager_tools_layer/src/filemanager_tools/utils/file_helpers.py
lib/workload/stateless/stacks/data-sharing-manager/ecs/tasks/generate_data_summary_report/data_summary_reporting_tools/src/data_summary_reporting_tools/models.py
lib/workload/stateless/stacks/data-sharing-manager/lambdas/create_script_from_presigned_urls_list_py/create_script_from_presigned_urls_list.py

Fixes presigned url request, phenotype may be a null value

Fix presigned url, phenotype nullable, and download path

---

config/stacks/postgresManager.ts

- Update metadata user to rds-iam
closes #202

feat(mm): Update metadata user to rds-iam

---

lib/workload/stateless/stacks/bclconvert-manager/deploy/stack.ts
lib/workload/stateless/stacks/bclconvert-manager/translator_service/helper/icav2_analysis/analysis_helper.py
lib/workload/stateless/stacks/bclconvert-manager/translator_service/icav2_event_translator.py

New BCLConvert Payload looks like this.
```
{
"version": "0",
"id": "0220c14e-25d3-0c66-82de-b0e63e2ba66d",
"detail-type": "Event from aws:sqs",
"source": "Pipe IcaEventPipeConstru-aVEAl34nl7zf",
"account": "843407916570",
"time": "2025-06-11T06:17:58Z",
"region": "ap-southeast-2",
"resources": [],
"detail": {
"ica-event": {
"correlationId": "307f7804-a799-40ed-8de7-a0dd3de9ead9",
"timestamp": "2025-06-11T06:17:57.936Z",
"eventCode": "ICA_EXEC_028",
"eventParameters": {
"pipelineExecution": "ecb3992e-06e3-4cc9-bc1f-82bcd35600d1",
"analysisPreviousStatus": "GENERATING_OUTPUTS",
"analysisStatus": "SUCCEEDED"
},
"description": "Analysis status changed",
"projectId": "a7c67a80-c8f2-4348-adec-3a5a073d1d55",
"payloadVersion": "v4",
"payload": {
"id": "ecb3992e-06e3-4cc9-bc1f-82bcd35600d1", …
```

Update BCLConvert Rule to allow BCLConvert to read new ORA pipeline

---

lib/workload/stateful/statefulStackCollectionClass.ts

- Migrate these stacks out to https://github.com/OrcaBus/service-shared-resources/pull/4

Chore: Migrate Stateful Stack

---

Makefile
lib/workload/stateless/stacks/fastq-manager/app/api/fastq_manager_api_tools/api/v1/routers/fastq_set.py
lib/workload/stateless/stacks/fastq-manager/deploy/stack.ts

Allows AWS Guard Duty agent to run in parallel,
Also small fix to function name in fastq manager.
And remove fastqSet/ prefix duplicate from validate endpoints

Add ecs managed policy for fargate tasks

---

lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/nails/part_1/initialise-library-db/index.ts
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/nails/part_1/initialise-library-db/lambdas/get_project_id_from_library_id_py/get_project_id_from_library_id.py
lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/nails/part_1/initialise-library-db/step_functions_templates/store_cttsov2_metadata_sfn_template.asl.json

LibraryInSampleSheet event, no longer emits the projectSet attribute, instead collect the project id from a lambda, and then initialise the library in the database entry

Update nails stack to collect project id from library orcabus id
